#!/usr/bin/env tsx
import * as fs from "fs"
import { createRequire } from "module"
import * as path from "path"
import { iconLibraries, type IconLibraryName } from "shadcn/icons"

import { materialSymbolNames } from "../examples/material-symbols-map"

type IconUsage = Record<IconLibraryName, Set<string>>

// [FORCE-UI-START] Material Symbols are raw SVGs, not a React-component package,
// so the preview barrel inlines each used SVG as a self-contained component
// (no SVGR / bundler config needed for the create app). Consumer output uses
// the ?react import shape via transform-icons instead.
const require = createRequire(import.meta.url)
const MS_ROUNDED_DIR = path.join(
  path.dirname(require.resolve("@material-symbols/svg-400/package.json")),
  "rounded"
)

function generateMaterialSymbolsBarrel(names: string[]): string {
  // String-keyed record (not function exports): svg-400 basenames like "delete"
  // are reserved words and cannot be identifiers.
  const entries = names.map((name) => {
    const svgPath = path.join(MS_ROUNDED_DIR, `${name}.svg`)
    const svg = fs.readFileSync(svgPath, "utf-8")
    const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1] ?? "0 -960 960 960"
    const inner = svg
      .replace(/^<svg[^>]*>/, "")
      .replace(/<\/svg>\s*$/, "")
      .trim()
    return `  ${JSON.stringify(name)}: (props: SVGProps<SVGSVGElement>) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" width="1em" height="1em" fill="currentColor" {...props}>${inner}</svg>
  ),`
  })
  return `/* eslint-disable */
// Auto-generated by scripts/build-icons.ts — inlined @material-symbols/svg-400 (rounded).
import type { FC, SVGProps } from "react"

export const icons: Record<string, FC<SVGProps<SVGSVGElement>>> = {
${entries.join("\n")}
}
`
}
// [FORCE-UI-END]

function findTsxFiles(dir: string) {
  const files: string[] = []
  const entries = fs.readdirSync(dir, { withFileTypes: true })

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      files.push(...findTsxFiles(fullPath))
    } else if (entry.isFile() && entry.name.endsWith(".tsx")) {
      files.push(fullPath)
    }
  }

  return files
}

function scanIconUsage() {
  const iconUsage: IconUsage = Object.keys(iconLibraries).reduce((acc, key) => {
    acc[key as IconLibraryName] = new Set()
    return acc
  }, {} as IconUsage)

  const registryBasesDir = path.join(process.cwd(), "registry/bases")
  const files = findTsxFiles(registryBasesDir)
  const libraryNames = Object.values(iconLibraries)
    .map((lib) => lib.name)
    .join("|")
  const iconPlaceholderRegex = new RegExp(
    `<IconPlaceholder\\s+([^>]*?)(?:${libraryNames})=["']([^"']+)["']([^>]*?)\\/?>`,
    "g"
  )

  for (const file of files) {
    const content = fs.readFileSync(file, "utf-8")

    let match
    while ((match = iconPlaceholderRegex.exec(content)) !== null) {
      const fullMatch = match[0]

      for (const [libraryName, config] of Object.entries(iconLibraries)) {
        const attrMatch = fullMatch.match(
          new RegExp(`${config.name}=["']([^"']+)["']`)
        )
        if (attrMatch) {
          iconUsage[libraryName as IconLibraryName].add(attrMatch[1])
        }
      }
    }
  }

  // [FORCE-UI] Docs/examples import Material Symbols directly via
  // @/examples/material-symbols; include that helper's icons in the inlined
  // preview barrel so Next can render them without SVGR.
  for (const iconName of Object.values(materialSymbolNames)) {
    iconUsage.materialSymbols.add(iconName)
  }

  return iconUsage
}

function generateIconFiles(iconUsage: IconUsage) {
  const outputDir = path.join(process.cwd(), "registry/icons")

  const written: string[] = []

  Object.entries(iconLibraries).forEach(([libraryName, config]) => {
    const icons = Array.from(iconUsage[libraryName as IconLibraryName]).sort()

    if (icons.length === 0) {
      return
    }

    // [FORCE-UI] Material Symbols: inline SVGs (.tsx); others: named re-exports (.ts).
    const isMaterial = libraryName === "materialSymbols"
    const content = isMaterial
      ? generateMaterialSymbolsBarrel(icons)
      : `// Auto-generated by scripts/build-icons.ts
${icons.map((icon) => `export { ${icon} } from "${config.export}"`).join("\n")}
`

    const filename = `__${libraryName}__.${isMaterial ? "tsx" : "ts"}`
    const filepath = path.join(outputDir, filename)

    // Skip unchanged files to avoid mtime bumps that trigger
    // unnecessary Turbopack invalidations in watch mode.
    if (
      fs.existsSync(filepath) &&
      fs.readFileSync(filepath, "utf-8") === content
    ) {
      return
    }

    fs.writeFileSync(filepath, content)
    written.push(`  - ${config.title}: ${icons.length} icons`)
  })

  if (written.length > 0) {
    console.log("✓ Generated icon files:")
    written.forEach((line) => console.log(line))
  }
}

function main() {
  const iconUsage = scanIconUsage()
  generateIconFiles(iconUsage)
}

const isWatchMode = process.argv.includes("--watch")

if (isWatchMode) {
  const REGISTRY_DIR = path.join(process.cwd(), "registry/bases")

  async function startWatcher() {
    const { default: chokidar } = await import("chokidar")

    main()

    const watcher = chokidar.watch(REGISTRY_DIR, {
      ignored: /(^|[/\\])\../,
      persistent: true,
      ignoreInitial: true,
    })

    const rebuild = (filename: string) => {
      if (!filename.endsWith(".tsx")) return

      try {
        main()
      } catch (error) {
        console.error("❌ Icons build failed:", error)
      }
    }

    watcher.on("error", (error) => {
      console.error("❌ Watcher error:", error)
    })

    watcher.on("change", rebuild)
    watcher.on("add", rebuild)

    process.on("SIGINT", async () => {
      await watcher.close()
      process.exit(0)
    })
  }

  startWatcher()
} else {
  main()
}
