version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/lead-design-tokens-cli"
    schedule:
      interval: "weekly"
