import type { PresetConfig } from "./preset"

export const DEFAULT_PRESETS = {
  nova: {
    title: "Nova",
    description: "Lucide / Geist",
    style: "nova",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "neutral",
    iconLibrary: "lucide",
    font: "geist",
    fontHeading: "inherit",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
    rtl: false,
  },
  vega: {
    title: "Vega",
    description: "Lucide / Inter",
    style: "vega",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "neutral",
    iconLibrary: "lucide",
    font: "inter",
    fontHeading: "inherit",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
    rtl: false,
  },
  maia: {
    title: "Maia",
    description: "Hugeicons / Figtree",
    style: "maia",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "neutral",
    iconLibrary: "hugeicons",
    font: "figtree",
    fontHeading: "inherit",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
    rtl: false,
  },
  lyra: {
    title: "Lyra",
    description: "Phosphor / JetBrains Mono",
    style: "lyra",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "neutral",
    iconLibrary: "phosphor",
    font: "jetbrains-mono",
    fontHeading: "inherit",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
    rtl: false,
  },
  mira: {
    title: "Mira",
    description: "Hugeicons / Inter",
    style: "mira",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "neutral",
    iconLibrary: "hugeicons",
    font: "inter",
    fontHeading: "inherit",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
    rtl: false,
  },
  luma: {
    title: "Luma",
    description: "Lucide / Inter",
    style: "luma",
    baseColor: "neutral",
    theme: "neutral",
    chartColor: "neutral",
    iconLibrary: "lucide",
    font: "inter",
    fontHeading: "inherit",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
    rtl: false,
  },
  sera: {
    title: "Sera",
    description: "Lucide / Noto Sans + Playfair Display",
    style: "sera",
    baseColor: "taupe",
    theme: "taupe",
    chartColor: "taupe",
    iconLibrary: "lucide",
    font: "noto-sans",
    fontHeading: "playfair-display",
    menuAccent: "subtle",
    menuColor: "default",
    radius: "default",
    rtl: false,
  },
} satisfies Record<
  PresetConfig["style"],
  PresetConfig & {
    description: string
    rtl: boolean
    title: string
  }
>
