#!/bin/bash

# Quick file transfer script for Termius users
# Since you have Termius access, you can use this with SFTP

SERVER="103.168.135.110"
SERVER_USER="root"
SERVER_PATH="/opt/ocean-erp"

echo "=========================================="
echo "Files to Transfer via Termius SFTP"
echo "=========================================="
echo ""
echo "Local files:"
echo "  /Users/marfreax/Github/ocean-erp/init-db/00-init.sql"
echo "  /Users/marfreax/Github/ocean-erp/init-database.sh"
echo ""
echo "Transfer to server:"
echo "  ${SERVER_PATH}/init-db/00-init.sql"
echo "  ${SERVER_PATH}/init-database.sh"
echo ""
echo "=========================================="
echo ""
echo "Option 1: Using Termius SFTP (Recommended)"
echo "=========================================="
echo "1. Open Termius"
echo "2. Connect to ${SERVER}"
echo "3. Use SFTP feature to upload files"
echo "4. Navigate to ${SERVER_PATH}"
echo "5. Upload the files listed above"
echo ""
echo "Option 2: Using scp command"
echo "=========================================="
echo "Run these commands:"
echo ""
echo "scp init-db/00-init.sql ${SERVER_USER}@${SERVER}:${SERVER_PATH}/init-db/"
echo "scp init-database.sh ${SERVER_USER}@${SERVER}:${SERVER_PATH}/"
echo ""
echo "Option 3: Copy-paste content via Termius"
echo "=========================================="
echo "If files are small, you can:"
echo "1. Cat the file locally: cat init-db/00-init.sql"
echo "2. Copy the output"
echo "3. In Termius: cat > /opt/ocean-erp/init-db/00-init.sql"
echo "4. Paste content"
echo "5. Press Ctrl+D to save"
echo ""
