title: "[blocks]: "
labels: ["Blocks Request"]
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for taking the time to create a block request! Please search open/closed requests before submitting, as the block or a similar one may have already been requested.

  - type: textarea
    id: block-description
    attributes:
      label: Description
      description: Tell us about your block request
      placeholder: "A dashboard for an e-commerce website showing sales, orders, and customers..."
    validations:
      required: true

  - type: input
    id: block-example-url
    attributes:
      label: Example
      description: Link to an example of the block
      placeholder: ex. https://example.com
    validations:
      required: false
