import dedent from "dedent"
import {
  registryItemFileSchema,
  registryItemSchema,
  type configSchema,
  type RegistryItem,
} from "shadcn/schema"
import { transformIcons, transformMenu, transformRender } from "shadcn/utils"
import { Project, ScriptKind } from "ts-morph"
import { z } from "zod"

import {
  buildRegistryBase,
  fonts,
  type DesignSystemConfig,
} from "@/registry/config"

const { Index } = await import("@/registry/bases/__index__")

// Builds a full v0 payload from a design system config.
export async function buildV0Payload(designSystemConfig: DesignSystemConfig) {
  const registryBase = buildRegistryBase(designSystemConfig)

  // Build all files in parallel.
  const [globalsCss, layoutFile, componentFiles] = await Promise.all([
    buildGlobalsCss(registryBase),
    buildLayoutFile(designSystemConfig),
    buildComponentFiles(designSystemConfig),
  ])

  return registryItemSchema.parse({
    name: designSystemConfig.item ?? "Item",
    type: "registry:item",
    dependencies: registryBase.dependencies,
    files: [globalsCss, layoutFile, ...componentFiles],
  })
}

function buildGlobalsCss(registryBase: RegistryItem) {
  const lightVars = Object.entries(registryBase.cssVars?.light ?? {})
    .map(([key, value]) => `  --${key}: ${value};`)
    .join("\n")

  const darkVars = Object.entries(registryBase.cssVars?.dark ?? {})
    .map(([key, value]) => `  --${key}: ${value};`)
    .join("\n")

  const content = dedent`@import "tailwindcss";
@import "tw-animate-css";
/* @import "shadcn/tailwind.css"; */

@custom-variant dark (&:is(.dark *));

@theme inline {
  --font-sans: var(--font-sans);
  --font-mono: var(--font-mono);
  --font-serif: var(--font-serif);
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --color-card: var(--card);
  --color-card-foreground: var(--card-foreground);
  --color-popover: var(--popover);
  --color-popover-foreground: var(--popover-foreground);
  --color-primary: var(--primary);
  --color-primary-foreground: var(--primary-foreground);
  --color-secondary: var(--secondary);
  --color-secondary-foreground: var(--secondary-foreground);
  --color-muted: var(--muted);
  --color-muted-foreground: var(--muted-foreground);
  --color-accent: var(--accent);
  --color-accent-foreground: var(--accent-foreground);
  --color-destructive: var(--destructive);
  --color-destructive-foreground: var(--destructive-foreground);
  --color-border: var(--border);
  --color-input: var(--input);
  --color-ring: var(--ring);
  --color-chart-1: var(--chart-1);
  --color-chart-2: var(--chart-2);
  --color-chart-3: var(--chart-3);
  --color-chart-4: var(--chart-4);
  --color-chart-5: var(--chart-5);
  --color-sidebar: var(--sidebar);
  --color-sidebar-foreground: var(--sidebar-foreground);
  --color-sidebar-primary: var(--sidebar-primary);
  --color-sidebar-primary-foreground: var(--sidebar-primary-foreground);
  --color-sidebar-accent: var(--sidebar-accent);
  --color-sidebar-accent-foreground: var(--sidebar-accent-foreground);
  --color-sidebar-border: var(--sidebar-border);
  --color-sidebar-ring: var(--sidebar-ring);
  --radius-sm: calc(var(--radius) * 0.6);
  --radius-md: calc(var(--radius) * 0.8);
  --radius-lg: var(--radius);
  --radius-xl: calc(var(--radius) * 1.4);
  --radius-2xl: calc(var(--radius) * 1.8);
  --radius-3xl: calc(var(--radius) * 2.2);
  --radius-4xl: calc(var(--radius) * 2.6);
}

:root {
  ${lightVars}
}

.dark {
  ${darkVars}
}

@layer base {
  * {
    @apply border-border outline-ring/50;
  }
  body {
    @apply bg-background text-foreground;
  }
}
  `

  return registryItemFileSchema.parse({
    path: "app/globals.css",
    type: "registry:file",
    target: "app/globals.css",
    content,
  })
}

function buildLayoutFile(designSystemConfig: DesignSystemConfig) {
  const font = fonts.find(
    (font) => font.name === `font-${designSystemConfig.font}`
  )
  if (!font) {
    throw new Error(`Font "${designSystemConfig.font}" not found`)
  }

  // Derive const name from the font's CSS variable (e.g. --font-sans → fontSans).
  const constName = font.font.variable
    .replace(/^--/, "")
    .replace(/-./g, (m) => m[1].toUpperCase())

  // Add font-serif or font-mono class to body when needed. Sans is the default.
  const fontClass =
    font.font.variable === "--font-serif"
      ? "font-serif"
      : font.font.variable === "--font-mono"
        ? "font-mono"
        : ""

  const bodyClassName = fontClass ? `antialiased ${fontClass}` : "antialiased"

  const content = dedent`
    import type { Metadata } from "next";
    import { ${font.font.import} } from "next/font/google";
    import "./globals.css";

    const ${constName} = ${font.font.import}({subsets:['latin'],variable:'${font.font.variable}'});

    export const metadata: Metadata = {
      title: "Create Next App",
      description: "Generated by create next app",
    };

    export default function RootLayout({
      children,
    }: Readonly<{
      children: React.ReactNode;
    }>) {
      return (
        <html lang="en" className={${constName}.variable}>
          <body
            className="${bodyClassName}"
          >
            {children}
          </body>
        </html>
      );
    }
  `

  return registryItemFileSchema.parse({
    path: "app/layout.tsx",
    type: "registry:page",
    target: "app/layout.tsx",
    content,
  })
}

async function buildComponentFiles(designSystemConfig: DesignSystemConfig) {
  const files = []
  const allItemsForBase = Object.values(Index[designSystemConfig.base])
    .filter((item: RegistryItem) => item.type === "registry:ui")
    .map((item) => item.name)

  // Fetch UI components and the item component in parallel.
  const itemComponentPromise = designSystemConfig.item
    ? getRegistryItemFile(designSystemConfig.item, designSystemConfig)
    : null

  const registryItemFiles = await Promise.all(
    allItemsForBase.map((name) => getRegistryItemFile(name, designSystemConfig))
  )
  files.push(...registryItemFiles)

  const pageFile = {
    path: "app/page.tsx",
    type: "registry:page",
    target: "app/page.tsx",
    content: dedent`
      export default function Page() {
        return (
          <div className="flex min-h-svh p-6">
            <div className="max-w-md text-sm leading-loose">
              <h1 className="font-medium">Project ready!</h1>
              <p>You may now prompt v0 to start building.</p>
              <a
                href="https://ui.shadcn.com/docs/new"
                target="_blank"
                rel="noopener noreferrer"
                className="mt-2 inline-flex text-primary underline underline-offset-4"
              >
                Read the docs
              </a>
            </div>
          </div>
        )
      }
    `,
  }

  // Build the actual item component.
  if (itemComponentPromise) {
    const itemComponentFile = await itemComponentPromise
    if (itemComponentFile) {
      // Find the export default function from the component file.
      const exportDefault = itemComponentFile.content.match(
        /export default function (\w+)/
      )
      if (exportDefault) {
        const functionName = exportDefault[1]

        // Replace the export default function with a named export.
        itemComponentFile.content = itemComponentFile.content.replace(
          /export default function (\w+)/,
          `export function ${functionName}`
        )

        // Import and render the item on the page.
        pageFile.content = dedent`import { ${functionName} } from "@/components/${designSystemConfig.item}";

        export default function Page() {
          return <${functionName} />
        }`
      }

      files.push({
        ...itemComponentFile,
        target: `components/${designSystemConfig.item}.tsx`,
        type: "registry:component",
      })
    }
  }

  files.push(pageFile)

  return z.array(registryItemFileSchema).parse(files)
}

async function getRegistryItemFile(
  name: string,
  designSystemConfig: DesignSystemConfig
) {
  const response = await fetch(
    `${process.env.NEXT_PUBLIC_APP_URL}/r/styles/${designSystemConfig.base}-${designSystemConfig.style}/${name}.json`
  )

  if (!response.ok) {
    throw new Error(`Failed to fetch registry item: ${response.statusText}`)
  }

  const json = await response.json()
  const item = registryItemSchema.parse(json)

  // Build a v0 config i.e components.json.
  const config = {
    $schema: "https://ui.shadcn.com/schema.json",
    style: `${designSystemConfig.base}-${designSystemConfig.style}`,
    rsc: true,
    tsx: true,
    tailwind: {
      config: "",
      css: "app/globals.css",
      baseColor: designSystemConfig.baseColor,
      cssVariables: true,
      prefix: "",
    },
    iconLibrary: designSystemConfig.iconLibrary,
    aliases: {
      components: "@/components",
      utils: "@/lib/utils",
      ui: "@/components/ui",
      lib: "@/lib",
      hooks: "@/hooks",
    },
    menuAccent: designSystemConfig.menuAccent,
    menuColor: designSystemConfig.menuColor,
    resolvedPaths: {
      cwd: "/",
      tailwindConfig: "./tailwind.config.js",
      tailwindCss: "./globals.css",
      utils: "./lib/utils",
      components: "./components",
      lib: "./lib",
      hooks: "./hooks",
      ui: "./components/ui",
    },
  } satisfies z.infer<typeof configSchema>

  const file = item.files?.[0]
  if (!file?.content) {
    return null
  }

  const content = await transformFileContent(file.content, config)

  return {
    ...file,
    target:
      name === "example"
        ? "components/example.tsx"
        : `components/ui/${name}.tsx`,
    type: name === "example" ? "registry:component" : "registry:ui",
    content,
  }
}

const transformers = [transformIcons, transformMenu, transformRender]

// Reuse a single ts-morph Project — avoids re-creating the compiler host per file.
const project = new Project({ compilerOptions: {} })

async function transformFileContent(
  content: string,
  config: z.infer<typeof configSchema>
) {
  const sourceFile = project.createSourceFile("component.tsx", content, {
    scriptKind: ScriptKind.TSX,
    overwrite: true,
  })

  for (const transformer of transformers) {
    await transformer({
      filename: "component.tsx",
      raw: content,
      sourceFile,
      config,
    })
  }

  return sourceFile.getText()
}
