"use client"

import { useParams } from "next/navigation"
import { TraceView } from "../components/trace-view"

export default function EventTracePage() {
  const params = useParams()
  const id = (params?.id as string) || ""
  const subtitle = "Anchor event lens showing inventory, journals, and payments generated by the event"

  return <TraceView resourceLabel="Event" resourceId={id} apiPath={`/api/trace/event/${encodeURIComponent(id)}`} subtitle={subtitle} />
}
