// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import "server-only"

import * as React from "react"

export const Components: Record<string, Record<string, any>> = {
  "radix-force-ui": {
    accordion: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/accordion")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "accordion"
      return { default: mod.default || mod[exportName] }
    }),
    alert: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/alert")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "alert"
      return { default: mod.default || mod[exportName] }
    }),
    "alert-dialog": React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/alert-dialog")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "alert-dialog"
      return { default: mod.default || mod[exportName] }
    }),
    "aspect-ratio": React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/aspect-ratio")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "aspect-ratio"
      return { default: mod.default || mod[exportName] }
    }),
    avatar: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/avatar")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "avatar"
      return { default: mod.default || mod[exportName] }
    }),
    badge: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/badge")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "badge"
      return { default: mod.default || mod[exportName] }
    }),
    breadcrumb: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/breadcrumb")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "breadcrumb"
      return { default: mod.default || mod[exportName] }
    }),
    button: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/button")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "button"
      return { default: mod.default || mod[exportName] }
    }),
    "button-group": React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/button-group")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "button-group"
      return { default: mod.default || mod[exportName] }
    }),
    calendar: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/calendar")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "calendar"
      return { default: mod.default || mod[exportName] }
    }),
    card: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/card")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "card"
      return { default: mod.default || mod[exportName] }
    }),
    carousel: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/carousel")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "carousel"
      return { default: mod.default || mod[exportName] }
    }),
    chart: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/chart")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "chart"
      return { default: mod.default || mod[exportName] }
    }),
    checkbox: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/checkbox")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "checkbox"
      return { default: mod.default || mod[exportName] }
    }),
    collapsible: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/collapsible")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "collapsible"
      return { default: mod.default || mod[exportName] }
    }),
    combobox: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/combobox")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "combobox"
      return { default: mod.default || mod[exportName] }
    }),
    command: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/command")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "command"
      return { default: mod.default || mod[exportName] }
    }),
    "context-menu": React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/context-menu")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "context-menu"
      return { default: mod.default || mod[exportName] }
    }),
    dialog: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/dialog")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "dialog"
      return { default: mod.default || mod[exportName] }
    }),
    drawer: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/drawer")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "drawer"
      return { default: mod.default || mod[exportName] }
    }),
    "dropdown-menu": React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/dropdown-menu")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "dropdown-menu"
      return { default: mod.default || mod[exportName] }
    }),
    empty: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/empty")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "empty"
      return { default: mod.default || mod[exportName] }
    }),
    field: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/field")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "field"
      return { default: mod.default || mod[exportName] }
    }),
    "hover-card": React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/hover-card")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "hover-card"
      return { default: mod.default || mod[exportName] }
    }),
    input: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/input")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "input"
      return { default: mod.default || mod[exportName] }
    }),
    "input-group": React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/input-group")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "input-group"
      return { default: mod.default || mod[exportName] }
    }),
    "input-otp": React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/input-otp")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "input-otp"
      return { default: mod.default || mod[exportName] }
    }),
    item: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/item")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "item"
      return { default: mod.default || mod[exportName] }
    }),
    label: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/label")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "label"
      return { default: mod.default || mod[exportName] }
    }),
    menubar: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/menubar")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "menubar"
      return { default: mod.default || mod[exportName] }
    }),
    "navigation-menu": React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/navigation-menu")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "navigation-menu"
      return { default: mod.default || mod[exportName] }
    }),
    pagination: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/pagination")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "pagination"
      return { default: mod.default || mod[exportName] }
    }),
    popover: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/popover")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "popover"
      return { default: mod.default || mod[exportName] }
    }),
    progress: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/progress")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "progress"
      return { default: mod.default || mod[exportName] }
    }),
    "radio-group": React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/radio-group")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "radio-group"
      return { default: mod.default || mod[exportName] }
    }),
    resizable: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/resizable")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "resizable"
      return { default: mod.default || mod[exportName] }
    }),
    "scroll-area": React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/scroll-area")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "scroll-area"
      return { default: mod.default || mod[exportName] }
    }),
    select: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/select")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "select"
      return { default: mod.default || mod[exportName] }
    }),
    separator: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/separator")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "separator"
      return { default: mod.default || mod[exportName] }
    }),
    sheet: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/sheet")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "sheet"
      return { default: mod.default || mod[exportName] }
    }),
    sidebar: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/sidebar")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "sidebar"
      return { default: mod.default || mod[exportName] }
    }),
    skeleton: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/skeleton")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "skeleton"
      return { default: mod.default || mod[exportName] }
    }),
    slider: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/slider")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "slider"
      return { default: mod.default || mod[exportName] }
    }),
    sonner: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/sonner")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "sonner"
      return { default: mod.default || mod[exportName] }
    }),
    spinner: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/spinner")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "spinner"
      return { default: mod.default || mod[exportName] }
    }),
    switch: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/switch")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "switch"
      return { default: mod.default || mod[exportName] }
    }),
    table: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/table")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "table"
      return { default: mod.default || mod[exportName] }
    }),
    tabs: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/tabs")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "tabs"
      return { default: mod.default || mod[exportName] }
    }),
    textarea: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/textarea")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "textarea"
      return { default: mod.default || mod[exportName] }
    }),
    toggle: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/toggle")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "toggle"
      return { default: mod.default || mod[exportName] }
    }),
    "toggle-group": React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/toggle-group")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "toggle-group"
      return { default: mod.default || mod[exportName] }
    }),
    tooltip: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/tooltip")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "tooltip"
      return { default: mod.default || mod[exportName] }
    }),
    kbd: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/kbd")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "kbd"
      return { default: mod.default || mod[exportName] }
    }),
    "native-select": React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/native-select")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "native-select"
      return { default: mod.default || mod[exportName] }
    }),
    direction: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/direction")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "direction"
      return { default: mod.default || mod[exportName] }
    }),
    attachment: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/attachment")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "attachment"
      return { default: mod.default || mod[exportName] }
    }),
    bubble: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/bubble")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "bubble"
      return { default: mod.default || mod[exportName] }
    }),
    "message-scroller": React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/message-scroller")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "message-scroller"
      return { default: mod.default || mod[exportName] }
    }),
    marker: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/marker")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "marker"
      return { default: mod.default || mod[exportName] }
    }),
    message: React.lazy(async () => {
      const mod = await import("@/styles/radix-force-ui/ui/message")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "message"
      return { default: mod.default || mod[exportName] }
    }),
  },
  "base-force-ui": {
    accordion: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/accordion")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "accordion"
      return { default: mod.default || mod[exportName] }
    }),
    alert: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/alert")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "alert"
      return { default: mod.default || mod[exportName] }
    }),
    "alert-dialog": React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/alert-dialog")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "alert-dialog"
      return { default: mod.default || mod[exportName] }
    }),
    "aspect-ratio": React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/aspect-ratio")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "aspect-ratio"
      return { default: mod.default || mod[exportName] }
    }),
    avatar: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/avatar")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "avatar"
      return { default: mod.default || mod[exportName] }
    }),
    badge: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/badge")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "badge"
      return { default: mod.default || mod[exportName] }
    }),
    breadcrumb: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/breadcrumb")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "breadcrumb"
      return { default: mod.default || mod[exportName] }
    }),
    button: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/button")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "button"
      return { default: mod.default || mod[exportName] }
    }),
    "button-group": React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/button-group")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "button-group"
      return { default: mod.default || mod[exportName] }
    }),
    calendar: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/calendar")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "calendar"
      return { default: mod.default || mod[exportName] }
    }),
    card: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/card")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "card"
      return { default: mod.default || mod[exportName] }
    }),
    carousel: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/carousel")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "carousel"
      return { default: mod.default || mod[exportName] }
    }),
    chart: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/chart")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "chart"
      return { default: mod.default || mod[exportName] }
    }),
    checkbox: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/checkbox")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "checkbox"
      return { default: mod.default || mod[exportName] }
    }),
    collapsible: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/collapsible")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "collapsible"
      return { default: mod.default || mod[exportName] }
    }),
    combobox: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/combobox")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "combobox"
      return { default: mod.default || mod[exportName] }
    }),
    command: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/command")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "command"
      return { default: mod.default || mod[exportName] }
    }),
    "context-menu": React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/context-menu")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "context-menu"
      return { default: mod.default || mod[exportName] }
    }),
    dialog: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/dialog")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "dialog"
      return { default: mod.default || mod[exportName] }
    }),
    drawer: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/drawer")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "drawer"
      return { default: mod.default || mod[exportName] }
    }),
    "dropdown-menu": React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/dropdown-menu")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "dropdown-menu"
      return { default: mod.default || mod[exportName] }
    }),
    empty: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/empty")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "empty"
      return { default: mod.default || mod[exportName] }
    }),
    field: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/field")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "field"
      return { default: mod.default || mod[exportName] }
    }),
    "hover-card": React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/hover-card")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "hover-card"
      return { default: mod.default || mod[exportName] }
    }),
    input: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/input")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "input"
      return { default: mod.default || mod[exportName] }
    }),
    "input-group": React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/input-group")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "input-group"
      return { default: mod.default || mod[exportName] }
    }),
    "input-otp": React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/input-otp")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "input-otp"
      return { default: mod.default || mod[exportName] }
    }),
    item: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/item")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "item"
      return { default: mod.default || mod[exportName] }
    }),
    label: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/label")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "label"
      return { default: mod.default || mod[exportName] }
    }),
    menubar: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/menubar")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "menubar"
      return { default: mod.default || mod[exportName] }
    }),
    "navigation-menu": React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/navigation-menu")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "navigation-menu"
      return { default: mod.default || mod[exportName] }
    }),
    pagination: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/pagination")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "pagination"
      return { default: mod.default || mod[exportName] }
    }),
    popover: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/popover")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "popover"
      return { default: mod.default || mod[exportName] }
    }),
    progress: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/progress")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "progress"
      return { default: mod.default || mod[exportName] }
    }),
    "radio-group": React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/radio-group")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "radio-group"
      return { default: mod.default || mod[exportName] }
    }),
    resizable: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/resizable")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "resizable"
      return { default: mod.default || mod[exportName] }
    }),
    "scroll-area": React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/scroll-area")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "scroll-area"
      return { default: mod.default || mod[exportName] }
    }),
    select: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/select")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "select"
      return { default: mod.default || mod[exportName] }
    }),
    separator: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/separator")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "separator"
      return { default: mod.default || mod[exportName] }
    }),
    sheet: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/sheet")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "sheet"
      return { default: mod.default || mod[exportName] }
    }),
    sidebar: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/sidebar")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "sidebar"
      return { default: mod.default || mod[exportName] }
    }),
    skeleton: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/skeleton")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "skeleton"
      return { default: mod.default || mod[exportName] }
    }),
    slider: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/slider")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "slider"
      return { default: mod.default || mod[exportName] }
    }),
    sonner: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/sonner")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "sonner"
      return { default: mod.default || mod[exportName] }
    }),
    spinner: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/spinner")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "spinner"
      return { default: mod.default || mod[exportName] }
    }),
    switch: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/switch")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "switch"
      return { default: mod.default || mod[exportName] }
    }),
    table: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/table")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "table"
      return { default: mod.default || mod[exportName] }
    }),
    tabs: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/tabs")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "tabs"
      return { default: mod.default || mod[exportName] }
    }),
    textarea: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/textarea")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "textarea"
      return { default: mod.default || mod[exportName] }
    }),
    toggle: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/toggle")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "toggle"
      return { default: mod.default || mod[exportName] }
    }),
    "toggle-group": React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/toggle-group")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "toggle-group"
      return { default: mod.default || mod[exportName] }
    }),
    tooltip: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/tooltip")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "tooltip"
      return { default: mod.default || mod[exportName] }
    }),
    kbd: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/kbd")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "kbd"
      return { default: mod.default || mod[exportName] }
    }),
    "native-select": React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/native-select")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "native-select"
      return { default: mod.default || mod[exportName] }
    }),
    direction: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/direction")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "direction"
      return { default: mod.default || mod[exportName] }
    }),
    attachment: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/attachment")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "attachment"
      return { default: mod.default || mod[exportName] }
    }),
    bubble: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/bubble")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "bubble"
      return { default: mod.default || mod[exportName] }
    }),
    "message-scroller": React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/message-scroller")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "message-scroller"
      return { default: mod.default || mod[exportName] }
    }),
    marker: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/marker")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "marker"
      return { default: mod.default || mod[exportName] }
    }),
    message: React.lazy(async () => {
      const mod = await import("@/styles/base-force-ui/ui/message")
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object"
        ) || "message"
      return { default: mod.default || mod[exportName] }
    }),
  },
  "vue-force-ui": {},
  "svelte-force-ui": {},
  "ember-force-ui": {},
}
