import { type RegistryItem } from "shadcn/schema"

export const fonts = [
  {
    name: "font-geist-sans",
    title: "Geist Sans",
    type: "registry:font",
    font: {
      family: "'Geist', sans-serif",
      provider: "local",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "Geist",
      path: "/fonts/geist/geist-v4-latin-regular.woff2",
    },
  },
  {
    name: "font-inter",
    title: "Inter",
    type: "registry:font",
    font: {
      family: "'Inter', sans-serif",
      provider: "local",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "Inter",
      path: "/fonts/inter/inter-v20-latin-regular.woff2",
    },
  },
  {
    name: "font-noto-sans",
    title: "Noto Sans",
    type: "registry:font",
    font: {
      family: "'Noto Sans', sans-serif",
      provider: "local",
      variable: "--font-sans",
      import: "Noto_Sans",
      path: "/fonts/noto-sans/noto-sans-v42-latin-regular.woff2",
    },
  },
  {
    name: "font-nunito-sans",
    title: "Nunito Sans",
    type: "registry:font",
    font: {
      family: "'Nunito Sans', sans-serif",
      provider: "local",
      variable: "--font-sans",
      import: "Nunito_Sans",
      path: "/fonts/nunito-sans/nunito-sans-v19-latin-regular.woff2",
    },
  },
  {
    name: "font-figtree",
    title: "Figtree",
    type: "registry:font",
    font: {
      family: "'Figtree', sans-serif",
      provider: "local",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "Figtree",
      path: "/fonts/figtree/figtree-v9-latin-regular.woff2",
    },
  },
  {
    name: "font-roboto",
    title: "Roboto",
    type: "registry:font",
    font: {
      family: "'Roboto', sans-serif",
      provider: "local",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "Roboto",
      path: "/fonts/roboto/roboto-v50-latin-regular.woff2",
    },
  },
  {
    name: "font-raleway",
    title: "Raleway",
    type: "registry:font",
    font: {
      family: "'Raleway', sans-serif",
      provider: "local",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "Raleway",
      path: "/fonts/raleway/raleway-v37-latin-regular.woff2",
    },
  },
  {
    name: "font-dm-sans",
    title: "DM Sans",
    type: "registry:font",
    font: {
      family: "'DM Sans', sans-serif",
      provider: "local",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "DM_Sans",
      path: "/fonts/dm-sans/dm-sans-v17-latin-regular.woff2",
    },
  },
  {
    name: "font-public-sans",
    title: "Public Sans",
    type: "registry:font",
    font: {
      family: "'Public Sans', sans-serif",
      provider: "local",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "Public_Sans",
      path: "/fonts/public-sans/public-sans-v21-latin-regular.woff2",
    },
  },
  {
    name: "font-outfit",
    title: "Outfit",
    type: "registry:font",
    font: {
      family: "'Outfit', sans-serif",
      provider: "local",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "Outfit",
      path: "/fonts/outfit/outfit-v15-latin-regular.woff2",
    },
  },
  {
    name: "font-jetbrains-mono",
    title: "JetBrains Mono",
    type: "registry:font",
    font: {
      family: "'JetBrains Mono', monospace",
      provider: "local",
      variable: "--font-sans",
      subsets: ["latin"],
      import: "JetBrains_Mono",
      path: "/fonts/jetbrains-mono/jetbrains-mono-v24-latin-regular.woff2",
    },
  },
  // {
  //   name: "font-geist-mono",
  //   title: "Geist Mono",
  //   type: "registry:font",
  //   font: {
  //     family: "'Geist Mono Variable', monospace",
  //     provider: "google",
  //     variable: "--font-sans",
  //     subsets: ["latin"],
  //     import: "Geist_Mono",
  //   },
  // },
] satisfies RegistryItem[]
