export const registryCategories = [
  {
    name: "Sidebar",
    slug: "sidebar",
    hidden: false,
    grid: 1,
  },
  {
    name: "Dashboard",
    slug: "dashboard",
    hidden: true,
    grid: 1,
  },
  {
    name: "Authentication",
    slug: "authentication",
    hidden: false,
    grid: 1,
  },
  {
    name: "Login",
    slug: "login",
    hidden: false,
    grid: 1,
  },
  {
    name: "Calendar",
    slug: "calendar",
    hidden: false,
    grid: 2,
  },
  {
    name: "Charts",
    slug: "charts",
    hidden: true,
    grid: 1,
  },
  {
    name: "Area Charts",
    slug: "charts-area",
    hidden: true,
    grid: 1,
  },
  {
    name: "Bar Charts",
    slug: "charts-bar",
    hidden: true,
    grid: 1,
  },
  {
    name: "Line Charts",
    slug: "charts-line",
    hidden: true,
    grid: 1,
  },
  {
    name: "Pie Charts",
    slug: "charts-pie",
    hidden: true,
    grid: 1,
  },
  {
    name: "Radar Charts",
    slug: "charts-radar",
    hidden: true,
    grid: 1,
  },
  {
    name: "Radial Charts",
    slug: "charts-radial",
    hidden: true,
    grid: 1,
  },
  {
    name: "Charts Tooltip",
    slug: "charts-tooltip",
    hidden: true,
    grid: 1,
  },
]
