import { Registry } from "@/registry/schema"

export const examples: Registry = [
  {
    name: "accordion-demo",
    type: "registry:example",
    registryDependencies: ["accordion"],
    files: ["example/accordion-demo.tsx"],
  },
  {
    name: "alert-demo",
    type: "registry:example",
    registryDependencies: ["alert"],
    files: ["example/alert-demo.tsx"],
  },
  {
    name: "alert-destructive",
    type: "registry:example",
    registryDependencies: ["alert"],
    files: ["example/alert-destructive.tsx"],
  },
  {
    name: "alert-dialog-demo",
    type: "registry:example",
    registryDependencies: ["alert-dialog", "button"],
    files: ["example/alert-dialog-demo.tsx"],
  },
  {
    name: "aspect-ratio-demo",
    type: "registry:example",
    registryDependencies: ["aspect-ratio"],
    files: ["example/aspect-ratio-demo.tsx"],
  },
  {
    name: "avatar-demo",
    type: "registry:example",
    registryDependencies: ["avatar"],
    files: ["example/avatar-demo.tsx"],
  },
  {
    name: "badge-demo",
    type: "registry:example",
    registryDependencies: ["badge"],
    files: ["example/badge-demo.tsx"],
  },
  {
    name: "badge-destructive",
    type: "registry:example",
    registryDependencies: ["badge"],
    files: ["example/badge-destructive.tsx"],
  },
  {
    name: "badge-outline",
    type: "registry:example",
    registryDependencies: ["badge"],
    files: ["example/badge-outline.tsx"],
  },
  {
    name: "badge-secondary",
    type: "registry:example",
    registryDependencies: ["badge"],
    files: ["example/badge-secondary.tsx"],
  },
  {
    name: "breadcrumb-demo",
    type: "registry:example",
    registryDependencies: ["breadcrumb"],
    files: ["example/breadcrumb-demo.tsx"],
  },
  {
    name: "breadcrumb-separator",
    type: "registry:example",
    registryDependencies: ["breadcrumb"],
    files: ["example/breadcrumb-separator.tsx"],
  },
  {
    name: "breadcrumb-dropdown",
    type: "registry:example",
    registryDependencies: ["breadcrumb"],
    files: ["example/breadcrumb-dropdown.tsx"],
  },
  {
    name: "breadcrumb-ellipsis",
    type: "registry:example",
    registryDependencies: ["breadcrumb"],
    files: ["example/breadcrumb-ellipsis.tsx"],
  },
  {
    name: "breadcrumb-link",
    type: "registry:example",
    registryDependencies: ["breadcrumb"],
    files: ["example/breadcrumb-link.tsx"],
  },
  {
    name: "breadcrumb-responsive",
    type: "registry:example",
    registryDependencies: ["breadcrumb"],
    files: ["example/breadcrumb-responsive.tsx"],
  },
  {
    name: "button-demo",
    type: "registry:example",
    registryDependencies: ["button"],
    files: ["example/button-demo.tsx"],
  },
  {
    name: "button-secondary",
    type: "registry:example",
    registryDependencies: ["button"],
    files: ["example/button-secondary.tsx"],
  },
  {
    name: "button-destructive",
    type: "registry:example",
    registryDependencies: ["button"],
    files: ["example/button-destructive.tsx"],
  },
  {
    name: "button-outline",
    type: "registry:example",
    registryDependencies: ["button"],
    files: ["example/button-outline.tsx"],
  },
  {
    name: "button-ghost",
    type: "registry:example",
    registryDependencies: ["button"],
    files: ["example/button-ghost.tsx"],
  },
  {
    name: "button-link",
    type: "registry:example",
    registryDependencies: ["button"],
    files: ["example/button-link.tsx"],
  },
  {
    name: "button-with-icon",
    type: "registry:example",
    registryDependencies: ["button"],
    files: ["example/button-with-icon.tsx"],
  },
  {
    name: "button-loading",
    type: "registry:example",
    registryDependencies: ["button"],
    files: ["example/button-loading.tsx"],
  },
  {
    name: "button-icon",
    type: "registry:example",
    registryDependencies: ["button"],
    files: ["example/button-icon.tsx"],
  },
  {
    name: "button-as-child",
    type: "registry:example",
    registryDependencies: ["button"],
    files: ["example/button-as-child.tsx"],
  },
  {
    name: "calendar-demo",
    type: "registry:example",
    registryDependencies: ["calendar"],
    files: ["example/calendar-demo.tsx"],
  },
  {
    name: "calendar-form",
    type: "registry:example",
    registryDependencies: ["calendar", "form", "popover"],
    files: ["example/calendar-form.tsx"],
  },
  {
    name: "card-demo",
    type: "registry:example",
    registryDependencies: ["card", "button", "switch"],
    files: ["example/card-demo.tsx"],
  },
  {
    name: "card-with-form",
    type: "registry:example",
    registryDependencies: ["button", "card", "input", "label", "select"],
    files: ["example/card-with-form.tsx"],
  },
  {
    name: "carousel-demo",
    type: "registry:example",
    registryDependencies: ["carousel"],
    files: ["example/carousel-demo.tsx"],
  },
  {
    name: "carousel-size",
    type: "registry:example",
    registryDependencies: ["carousel"],
    files: ["example/carousel-size.tsx"],
  },
  {
    name: "carousel-spacing",
    type: "registry:example",
    registryDependencies: ["carousel"],
    files: ["example/carousel-spacing.tsx"],
  },
  {
    name: "carousel-orientation",
    type: "registry:example",
    registryDependencies: ["carousel"],
    files: ["example/carousel-orientation.tsx"],
  },
  {
    name: "carousel-api",
    type: "registry:example",
    registryDependencies: ["carousel"],
    files: ["example/carousel-api.tsx"],
  },
  {
    name: "carousel-plugin",
    type: "registry:example",
    registryDependencies: ["carousel"],
    files: ["example/carousel-plugin.tsx"],
  },
  {
    name: "checkbox-demo",
    type: "registry:example",
    registryDependencies: ["checkbox"],
    files: ["example/checkbox-demo.tsx"],
  },
  {
    name: "checkbox-disabled",
    type: "registry:example",
    registryDependencies: ["checkbox"],
    files: ["example/checkbox-disabled.tsx"],
  },
  {
    name: "checkbox-form-multiple",
    type: "registry:example",
    registryDependencies: ["checkbox", "form"],
    files: ["example/checkbox-form-multiple.tsx"],
  },
  {
    name: "checkbox-form-single",
    type: "registry:example",
    registryDependencies: ["checkbox", "form"],
    files: ["example/checkbox-form-single.tsx"],
  },
  {
    name: "checkbox-with-text",
    type: "registry:example",
    registryDependencies: ["checkbox"],
    files: ["example/checkbox-with-text.tsx"],
  },
  {
    name: "collapsible-demo",
    type: "registry:example",
    registryDependencies: ["collapsible"],
    files: ["example/collapsible-demo.tsx"],
  },
  {
    name: "combobox-demo",
    type: "registry:example",
    registryDependencies: ["command"],
    files: ["example/combobox-demo.tsx"],
  },
  {
    name: "combobox-dropdown-menu",
    type: "registry:example",
    registryDependencies: ["command", "dropdown-menu", "button"],
    files: ["example/combobox-dropdown-menu.tsx"],
  },
  {
    name: "combobox-form",
    type: "registry:example",
    registryDependencies: ["command", "form"],
    files: ["example/combobox-form.tsx"],
  },
  {
    name: "combobox-popover",
    type: "registry:example",
    registryDependencies: ["combobox", "popover"],
    files: ["example/combobox-popover.tsx"],
  },
  {
    name: "combobox-responsive",
    type: "registry:example",
    registryDependencies: ["combobox", "popover", "drawer"],
    files: ["example/combobox-responsive.tsx"],
  },
  {
    name: "command-demo",
    type: "registry:example",
    registryDependencies: ["command"],
    files: ["example/command-demo.tsx"],
  },
  {
    name: "command-dialog",
    type: "registry:example",
    registryDependencies: ["command", "dialog"],
    files: ["example/command-dialog.tsx"],
  },
  {
    name: "context-menu-demo",
    type: "registry:example",
    registryDependencies: ["context-menu"],
    files: ["example/context-menu-demo.tsx"],
  },
  {
    name: "data-table-demo",
    type: "registry:example",
    registryDependencies: ["data-table"],
    files: ["example/data-table-demo.tsx"],
  },
  {
    name: "date-picker-demo",
    type: "registry:example",
    registryDependencies: ["button", "calendar", "popover"],
    files: ["example/date-picker-demo.tsx"],
    dependencies: ["date-fns"],
  },
  {
    name: "date-picker-form",
    type: "registry:example",
    registryDependencies: ["button", "calendar", "form", "popover"],
    files: ["example/date-picker-form.tsx"],
    dependencies: ["date-fns"],
  },
  {
    name: "date-picker-with-presets",
    type: "registry:example",
    registryDependencies: ["button", "calendar", "popover", "select"],
    files: ["example/date-picker-with-presets.tsx"],
    dependencies: ["date-fns"],
  },
  {
    name: "date-picker-with-range",
    type: "registry:example",
    registryDependencies: ["button", "calendar", "popover"],
    files: ["example/date-picker-with-range.tsx"],
    dependencies: ["date-fns"],
  },
  {
    name: "dialog-demo",
    type: "registry:example",
    registryDependencies: ["dialog"],
    files: ["example/dialog-demo.tsx"],
  },
  {
    name: "dialog-close-button",
    type: "registry:example",
    registryDependencies: ["dialog", "button"],
    files: ["example/dialog-close-button.tsx"],
  },
  {
    name: "drawer-demo",
    type: "registry:example",
    registryDependencies: ["drawer"],
    files: ["example/drawer-demo.tsx"],
  },
  {
    name: "drawer-dialog",
    type: "registry:example",
    registryDependencies: ["drawer", "dialog"],
    files: ["example/drawer-dialog.tsx"],
  },
  {
    name: "dropdown-menu-demo",
    type: "registry:example",
    registryDependencies: ["dropdown-menu"],
    files: ["example/dropdown-menu-demo.tsx"],
  },
  {
    name: "dropdown-menu-checkboxes",
    type: "registry:example",
    registryDependencies: ["dropdown-menu", "checkbox"],
    files: ["example/dropdown-menu-checkboxes.tsx"],
  },
  {
    name: "dropdown-menu-radio-group",
    type: "registry:example",
    registryDependencies: ["dropdown-menu", "radio-group"],
    files: ["example/dropdown-menu-radio-group.tsx"],
  },
  {
    name: "hover-card-demo",
    type: "registry:example",
    registryDependencies: ["hover-card"],
    files: ["example/hover-card-demo.tsx"],
  },
  {
    name: "input-demo",
    type: "registry:example",
    registryDependencies: ["input"],
    files: ["example/input-demo.tsx"],
  },
  {
    name: "input-disabled",
    type: "registry:example",
    registryDependencies: ["input"],
    files: ["example/input-disabled.tsx"],
  },
  {
    name: "input-file",
    type: "registry:example",
    registryDependencies: ["input"],
    files: ["example/input-file.tsx"],
  },
  {
    name: "input-form",
    type: "registry:example",
    registryDependencies: ["input", "button", "form"],
    files: ["example/input-form.tsx"],
  },
  {
    name: "input-with-button",
    type: "registry:example",
    registryDependencies: ["input", "button"],
    files: ["example/input-with-button.tsx"],
  },
  {
    name: "input-with-label",
    type: "registry:example",
    registryDependencies: ["input", "button", "label"],
    files: ["example/input-with-label.tsx"],
  },
  {
    name: "input-with-text",
    type: "registry:example",
    registryDependencies: ["input", "button", "label"],
    files: ["example/input-with-text.tsx"],
  },
  {
    name: "input-otp-demo",
    type: "registry:example",
    registryDependencies: ["input-otp"],
    files: ["example/input-otp-demo.tsx"],
  },
  {
    name: "input-otp-pattern",
    type: "registry:example",
    registryDependencies: ["input-otp"],
    files: ["example/input-otp-pattern.tsx"],
  },
  {
    name: "input-otp-separator",
    type: "registry:example",
    registryDependencies: ["input-otp"],
    files: ["example/input-otp-separator.tsx"],
  },
  {
    name: "input-otp-controlled",
    type: "registry:example",
    registryDependencies: ["input-otp"],
    files: ["example/input-otp-controlled.tsx"],
  },
  {
    name: "input-otp-form",
    type: "registry:example",
    registryDependencies: ["input-otp", "form"],
    files: ["example/input-otp-form.tsx"],
  },
  {
    name: "label-demo",
    type: "registry:example",
    registryDependencies: ["label"],
    files: ["example/label-demo.tsx"],
  },
  {
    name: "menubar-demo",
    type: "registry:example",
    registryDependencies: ["menubar"],
    files: ["example/menubar-demo.tsx"],
  },
  {
    name: "navigation-menu-demo",
    type: "registry:example",
    registryDependencies: ["navigation-menu"],
    files: ["example/navigation-menu-demo.tsx"],
  },
  {
    name: "pagination-demo",
    type: "registry:example",
    registryDependencies: ["pagination"],
    files: ["example/pagination-demo.tsx"],
  },
  {
    name: "popover-demo",
    type: "registry:example",
    registryDependencies: ["popover"],
    files: ["example/popover-demo.tsx"],
  },
  {
    name: "progress-demo",
    type: "registry:example",
    registryDependencies: ["progress"],
    files: ["example/progress-demo.tsx"],
  },
  {
    name: "radio-group-demo",
    type: "registry:example",
    registryDependencies: ["radio-group"],
    files: ["example/radio-group-demo.tsx"],
  },
  {
    name: "radio-group-form",
    type: "registry:example",
    registryDependencies: ["radio-group", "form"],
    files: ["example/radio-group-form.tsx"],
  },
  {
    name: "resizable-demo",
    type: "registry:example",
    registryDependencies: ["resizable"],
    files: ["example/resizable-demo.tsx"],
  },
  {
    name: "resizable-demo-with-handle",
    type: "registry:example",
    registryDependencies: ["resizable"],
    files: ["example/resizable-demo-with-handle.tsx"],
  },
  {
    name: "resizable-vertical",
    type: "registry:example",
    registryDependencies: ["resizable"],
    files: ["example/resizable-vertical.tsx"],
  },
  {
    name: "resizable-handle",
    type: "registry:example",
    registryDependencies: ["resizable"],
    files: ["example/resizable-handle.tsx"],
  },
  {
    name: "scroll-area-demo",
    type: "registry:example",
    registryDependencies: ["scroll-area"],
    files: ["example/scroll-area-demo.tsx"],
  },
  {
    name: "scroll-area-horizontal-demo",
    type: "registry:example",
    registryDependencies: ["scroll-area"],
    files: ["example/scroll-area-horizontal-demo.tsx"],
  },
  {
    name: "select-demo",
    type: "registry:example",
    registryDependencies: ["select"],
    files: ["example/select-demo.tsx"],
  },
  {
    name: "select-scrollable",
    type: "registry:example",
    registryDependencies: ["select"],
    files: ["example/select-scrollable.tsx"],
  },
  {
    name: "select-form",
    type: "registry:example",
    registryDependencies: ["select"],
    files: ["example/select-form.tsx"],
  },
  {
    name: "separator-demo",
    type: "registry:example",
    registryDependencies: ["separator"],
    files: ["example/separator-demo.tsx"],
  },
  {
    name: "sheet-demo",
    type: "registry:example",
    registryDependencies: ["sheet"],
    files: ["example/sheet-demo.tsx"],
  },
  {
    name: "sheet-side",
    type: "registry:example",
    registryDependencies: ["sheet"],
    files: ["example/sheet-side.tsx"],
  },
  {
    name: "skeleton-demo",
    type: "registry:example",
    registryDependencies: ["skeleton"],
    files: ["example/skeleton-demo.tsx"],
  },
  {
    name: "skeleton-card",
    type: "registry:example",
    registryDependencies: ["skeleton"],
    files: ["example/skeleton-card.tsx"],
  },
  {
    name: "slider-demo",
    type: "registry:example",
    registryDependencies: ["slider"],
    files: ["example/slider-demo.tsx"],
  },
  {
    name: "sonner-demo",
    type: "registry:example",
    registryDependencies: ["sonner"],
    files: ["example/sonner-demo.tsx"],
  },
  {
    name: "switch-demo",
    type: "registry:example",
    registryDependencies: ["switch"],
    files: ["example/switch-demo.tsx"],
  },
  {
    name: "switch-form",
    type: "registry:example",
    registryDependencies: ["switch", "form"],
    files: ["example/switch-form.tsx"],
  },
  {
    name: "table-demo",
    type: "registry:example",
    registryDependencies: ["table"],
    files: ["example/table-demo.tsx"],
  },
  {
    name: "tabs-demo",
    type: "registry:example",
    registryDependencies: ["tabs"],
    files: ["example/tabs-demo.tsx"],
  },
  {
    name: "textarea-demo",
    type: "registry:example",
    registryDependencies: ["textarea"],
    files: ["example/textarea-demo.tsx"],
  },
  {
    name: "textarea-disabled",
    type: "registry:example",
    registryDependencies: ["textarea"],
    files: ["example/textarea-disabled.tsx"],
  },
  {
    name: "textarea-form",
    type: "registry:example",
    registryDependencies: ["textarea", "form"],
    files: ["example/textarea-form.tsx"],
  },
  {
    name: "textarea-with-button",
    type: "registry:example",
    registryDependencies: ["textarea", "button"],
    files: ["example/textarea-with-button.tsx"],
  },
  {
    name: "textarea-with-label",
    type: "registry:example",
    registryDependencies: ["textarea", "label"],
    files: ["example/textarea-with-label.tsx"],
  },
  {
    name: "textarea-with-text",
    type: "registry:example",
    registryDependencies: ["textarea", "label"],
    files: ["example/textarea-with-text.tsx"],
  },
  {
    name: "toast-demo",
    type: "registry:example",
    registryDependencies: ["toast"],
    files: ["example/toast-demo.tsx"],
  },
  {
    name: "toast-destructive",
    type: "registry:example",
    registryDependencies: ["toast"],
    files: ["example/toast-destructive.tsx"],
  },
  {
    name: "toast-simple",
    type: "registry:example",
    registryDependencies: ["toast"],
    files: ["example/toast-simple.tsx"],
  },
  {
    name: "toast-with-action",
    type: "registry:example",
    registryDependencies: ["toast"],
    files: ["example/toast-with-action.tsx"],
  },
  {
    name: "toast-with-title",
    type: "registry:example",
    registryDependencies: ["toast"],
    files: ["example/toast-with-title.tsx"],
  },
  {
    name: "toggle-group-demo",
    type: "registry:example",
    registryDependencies: ["toggle-group"],
    files: ["example/toggle-group-demo.tsx"],
  },
  {
    name: "toggle-group-disabled",
    type: "registry:example",
    registryDependencies: ["toggle-group"],
    files: ["example/toggle-group-disabled.tsx"],
  },
  {
    name: "toggle-group-lg",
    type: "registry:example",
    registryDependencies: ["toggle-group"],
    files: ["example/toggle-group-lg.tsx"],
  },
  {
    name: "toggle-group-outline",
    type: "registry:example",
    registryDependencies: ["toggle-group"],
    files: ["example/toggle-group-outline.tsx"],
  },
  {
    name: "toggle-group-sm",
    type: "registry:example",
    registryDependencies: ["toggle-group"],
    files: ["example/toggle-group-sm.tsx"],
  },
  {
    name: "toggle-group-single",
    type: "registry:example",
    registryDependencies: ["toggle-group"],
    files: ["example/toggle-group-single.tsx"],
  },
  {
    name: "toggle-demo",
    type: "registry:example",
    registryDependencies: ["toggle"],
    files: ["example/toggle-demo.tsx"],
  },
  {
    name: "toggle-disabled",
    type: "registry:example",
    registryDependencies: ["toggle"],
    files: ["example/toggle-disabled.tsx"],
  },
  {
    name: "toggle-lg",
    type: "registry:example",
    registryDependencies: ["toggle"],
    files: ["example/toggle-lg.tsx"],
  },
  {
    name: "toggle-outline",
    type: "registry:example",
    registryDependencies: ["toggle"],
    files: ["example/toggle-outline.tsx"],
  },
  {
    name: "toggle-sm",
    type: "registry:example",
    registryDependencies: ["toggle"],
    files: ["example/toggle-sm.tsx"],
  },
  {
    name: "toggle-with-text",
    type: "registry:example",
    registryDependencies: ["toggle"],
    files: ["example/toggle-with-text.tsx"],
  },
  {
    name: "tooltip-demo",
    type: "registry:example",
    registryDependencies: ["tooltip"],
    files: ["example/tooltip-demo.tsx"],
  },
  {
    name: "typography-blockquote",
    type: "registry:example",
    files: ["example/typography-blockquote.tsx"],
  },
  {
    name: "typography-demo",
    type: "registry:example",
    files: ["example/typography-demo.tsx"],
  },
  {
    name: "typography-h1",
    type: "registry:example",
    files: ["example/typography-h1.tsx"],
  },
  {
    name: "typography-h2",
    type: "registry:example",
    files: ["example/typography-h2.tsx"],
  },
  {
    name: "typography-h3",
    type: "registry:example",
    files: ["example/typography-h3.tsx"],
  },
  {
    name: "typography-h4",
    type: "registry:example",
    files: ["example/typography-h4.tsx"],
  },
  {
    name: "typography-inline-code",
    type: "registry:example",
    files: ["example/typography-inline-code.tsx"],
  },
  {
    name: "typography-large",
    type: "registry:example",
    files: ["example/typography-large.tsx"],
  },
  {
    name: "typography-lead",
    type: "registry:example",
    files: ["example/typography-lead.tsx"],
  },
  {
    name: "typography-list",
    type: "registry:example",
    files: ["example/typography-list.tsx"],
  },
  {
    name: "typography-muted",
    type: "registry:example",
    files: ["example/typography-muted.tsx"],
  },
  {
    name: "typography-p",
    type: "registry:example",
    files: ["example/typography-p.tsx"],
  },
  {
    name: "typography-small",
    type: "registry:example",
    files: ["example/typography-small.tsx"],
  },
  {
    name: "typography-table",
    type: "registry:example",
    files: ["example/typography-table.tsx"],
  },
  {
    name: "mode-toggle",
    type: "registry:example",
    files: ["example/mode-toggle.tsx"],
  },
  {
    name: "chart-bar-demo",
    type: "registry:example",
    files: ["example/chart-bar-demo.tsx"],
  },
  {
    name: "chart-bar-demo-grid",
    type: "registry:example",
    files: ["example/chart-bar-demo-grid.tsx"],
  },
  {
    name: "chart-bar-demo-axis",
    type: "registry:example",
    files: ["example/chart-bar-demo-axis.tsx"],
  },
  {
    name: "chart-bar-demo-tooltip",
    type: "registry:example",
    files: ["example/chart-bar-demo-tooltip.tsx"],
  },
  {
    name: "chart-bar-demo-legend",
    type: "registry:example",
    files: ["example/chart-bar-demo-legend.tsx"],
  },
  {
    name: "chart-tooltip-demo",
    type: "registry:example",
    files: ["example/chart-tooltip-demo.tsx"],
  },
]
