import { type Registry } from "shadcn/schema"

export const blocks: Registry["items"] = [
  {
    name: "preview",
    title: "Home",
    type: "registry:block",
    registryDependencies: [
      "alert-dialog",
      "avatar",
      "badge",
      "button",
      "button-group",
      "card",
      "checkbox",
      "combobox",
      "dropdown-menu",
      "empty",
      "field",
      "input",
      "input-group",
      "item",
      "label",
      "popover",
      "radio-group",
      "select",
      "separator",
      "sheet",
      "slider",
      "spinner",
      "switch",
      "textarea",
      "tooltip",
      "example",
    ],
    files: [
      {
        path: "blocks/preview.tsx",
        type: "registry:block",
      },
    ],
  },
  {
    name: "elevenlabs",
    title: "Elevenlabs",
    type: "registry:block",
    registryDependencies: ["example", "button", "card"],
    files: [
      {
        path: "blocks/elevenlabs.tsx",
        type: "registry:block",
      },
    ],
  },
  {
    name: "github",
    title: "GitHub",
    type: "registry:block",
    registryDependencies: [
      "avatar",
      "badge",
      "button",
      "card",
      "checkbox",
      "combobox",
      "command",
      "drawer",
      "dropdown-menu",
      "empty",
      "field",
      "input",
      "input-group",
      "item",
      "kbd",
      "native-select",
      "popover",
      "separator",
      "spinner",
      "tabs",
      "textarea",
      "tooltip",
      "example",
    ],
    files: [
      {
        path: "blocks/github.tsx",
        type: "registry:block",
      },
    ],
  },
  {
    name: "vercel",
    title: "Vercel",
    type: "registry:block",
    registryDependencies: [
      "alert",
      "badge",
      "button",
      "calendar",
      "card",
      "chart",
      "dialog",
      "dropdown-menu",
      "empty",
      "field",
      "input-group",
      "item",
      "native-select",
      "popover",
      "textarea",
      "example",
    ],
    files: [
      {
        path: "blocks/vercel.tsx",
        type: "registry:block",
      },
    ],
  },
  {
    name: "chatgpt",
    title: "ChatGPT",
    type: "registry:block",
    registryDependencies: [
      "alert",
      "alert-dialog",
      "badge",
      "button",
      "card",
      "dropdown-menu",
      "field",
      "input-group",
      "item",
      "kbd",
      "popover",
      "tooltip",
      "example",
    ],
    files: [
      {
        path: "blocks/chatgpt.tsx",
        type: "registry:block",
      },
    ],
  },
]
