import type { FC, SVGProps } from "react"
import { materialSymbolNames } from "@/examples/material-symbols-map"

import { icons } from "@/registry/icons/__materialSymbols__"

type IconComponent = FC<SVGProps<SVGSVGElement>>
const getIcon = (name: string) => icons[name] as IconComponent

export const AlertCircleIcon = getIcon(materialSymbolNames.AlertCircleIcon)
export const AlertTriangleIcon = getIcon(materialSymbolNames.AlertTriangleIcon)
export const AppWindowIcon = getIcon(materialSymbolNames.AppWindowIcon)
export const ArchiveIcon = getIcon(materialSymbolNames.ArchiveIcon)
export const ArrowLeftIcon = getIcon(materialSymbolNames.ArrowLeftIcon)
export const ArrowRightIcon = getIcon(materialSymbolNames.ArrowRightIcon)
export const ArrowUpDown = getIcon(materialSymbolNames.ArrowUpDown)
export const ArrowUpIcon = getIcon(materialSymbolNames.ArrowUpIcon)
export const ArrowUpRightIcon = getIcon(materialSymbolNames.ArrowUpRightIcon)
export const AudioLinesIcon = getIcon(materialSymbolNames.AudioLinesIcon)
export const AudioWaveform = getIcon(materialSymbolNames.AudioWaveform)
export const BadgeCheck = getIcon(materialSymbolNames.BadgeCheck)
export const BadgeCheckIcon = getIcon(materialSymbolNames.BadgeCheckIcon)
export const Bell = getIcon(materialSymbolNames.Bell)
export const BellIcon = getIcon(materialSymbolNames.BellIcon)
export const BluetoothIcon = getIcon(materialSymbolNames.BluetoothIcon)
export const Bold = getIcon(materialSymbolNames.Bold)
export const BoldIcon = getIcon(materialSymbolNames.BoldIcon)
export const BookmarkIcon = getIcon(materialSymbolNames.BookmarkIcon)
export const BookOpen = getIcon(materialSymbolNames.BookOpen)
export const Bot = getIcon(materialSymbolNames.Bot)
export const BotIcon = getIcon(materialSymbolNames.BotIcon)
export const Building2Icon = getIcon(materialSymbolNames.Building2Icon)
export const Calculator = getIcon(materialSymbolNames.Calculator)
export const CalculatorIcon = getIcon(materialSymbolNames.CalculatorIcon)
export const Calendar = getIcon(materialSymbolNames.Calendar)
export const CalendarIcon = getIcon(materialSymbolNames.CalendarIcon)
export const CalendarPlusIcon = getIcon(materialSymbolNames.CalendarPlusIcon)
export const CheckCircle2Icon = getIcon(materialSymbolNames.CheckCircle2Icon)
export const CheckIcon = getIcon(materialSymbolNames.CheckIcon)
export const ChevronDown = getIcon(materialSymbolNames.ChevronDown)
export const ChevronDownIcon = getIcon(materialSymbolNames.ChevronDownIcon)
export const ChevronLeftIcon = getIcon(materialSymbolNames.ChevronLeftIcon)
export const ChevronRight = getIcon(materialSymbolNames.ChevronRight)
export const ChevronRightIcon = getIcon(materialSymbolNames.ChevronRightIcon)
export const ChevronsUpDown = getIcon(materialSymbolNames.ChevronsUpDown)
export const ChevronUpIcon = getIcon(materialSymbolNames.ChevronUpIcon)
export const CircleAlertIcon = getIcon(materialSymbolNames.CircleAlertIcon)
export const CircleCheckIcon = getIcon(materialSymbolNames.CircleCheckIcon)
export const CircleDashedIcon = getIcon(materialSymbolNames.CircleDashedIcon)
export const CircleFadingArrowUpIcon = getIcon(
  materialSymbolNames.CircleFadingArrowUpIcon
)
export const CircleFadingPlusIcon = getIcon(
  materialSymbolNames.CircleFadingPlusIcon
)
export const ClipboardPasteIcon = getIcon(
  materialSymbolNames.ClipboardPasteIcon
)
export const Clock2Icon = getIcon(materialSymbolNames.Clock2Icon)
export const ClockIcon = getIcon(materialSymbolNames.ClockIcon)
export const CodeIcon = getIcon(materialSymbolNames.CodeIcon)
export const Command = getIcon(materialSymbolNames.Command)
export const CopyIcon = getIcon(materialSymbolNames.CopyIcon)
export const CreditCard = getIcon(materialSymbolNames.CreditCard)
export const CreditCardIcon = getIcon(materialSymbolNames.CreditCardIcon)
export const DotIcon = getIcon(materialSymbolNames.DotIcon)
export const DownloadIcon = getIcon(materialSymbolNames.DownloadIcon)
export const ExternalLinkIcon = getIcon(materialSymbolNames.ExternalLinkIcon)
export const EyeIcon = getIcon(materialSymbolNames.EyeIcon)
export const EyeOffIcon = getIcon(materialSymbolNames.EyeOffIcon)
export const FileCodeIcon = getIcon(materialSymbolNames.FileCodeIcon)
export const FileIcon = getIcon(materialSymbolNames.FileIcon)
export const FileTextIcon = getIcon(materialSymbolNames.FileTextIcon)
export const Folder = getIcon(materialSymbolNames.Folder)
export const FolderIcon = getIcon(materialSymbolNames.FolderIcon)
export const FolderOpenIcon = getIcon(materialSymbolNames.FolderOpenIcon)
export const FolderPlusIcon = getIcon(materialSymbolNames.FolderPlusIcon)
export const FolderSearchIcon = getIcon(materialSymbolNames.FolderSearchIcon)
export const Forward = getIcon(materialSymbolNames.Forward)
export const Frame = getIcon(materialSymbolNames.Frame)
export const FrameIcon = getIcon(materialSymbolNames.FrameIcon)
export const GalleryVerticalEnd = getIcon(
  materialSymbolNames.GalleryVerticalEnd
)
export const GlobeIcon = getIcon(materialSymbolNames.GlobeIcon)
export const HelpCircle = getIcon(materialSymbolNames.HelpCircle)
export const HelpCircleIcon = getIcon(materialSymbolNames.HelpCircleIcon)
export const HomeIcon = getIcon(materialSymbolNames.HomeIcon)
export const IconBell = getIcon(materialSymbolNames.IconBell)
export const IconBrandJavascript = getIcon(
  materialSymbolNames.IconBrandJavascript
)
export const IconCheck = getIcon(materialSymbolNames.IconCheck)
export const IconCloud = getIcon(materialSymbolNames.IconCloud)
export const IconCopy = getIcon(materialSymbolNames.IconCopy)
export const IconCornerDownLeft = getIcon(
  materialSymbolNames.IconCornerDownLeft
)
export const IconFolderCode = getIcon(materialSymbolNames.IconFolderCode)
export const IconGitBranch = getIcon(materialSymbolNames.IconGitBranch)
export const IconGitFork = getIcon(materialSymbolNames.IconGitFork)
export const IconInfoCircle = getIcon(materialSymbolNames.IconInfoCircle)
export const IconPlus = getIcon(materialSymbolNames.IconPlus)
export const IconRefresh = getIcon(materialSymbolNames.IconRefresh)
export const IconStar = getIcon(materialSymbolNames.IconStar)
export const ImageIcon = getIcon(materialSymbolNames.ImageIcon)
export const InboxIcon = getIcon(materialSymbolNames.InboxIcon)
export const InfoIcon = getIcon(materialSymbolNames.InfoIcon)
export const Italic = getIcon(materialSymbolNames.Italic)
export const ItalicIcon = getIcon(materialSymbolNames.ItalicIcon)
export const KeyboardIcon = getIcon(materialSymbolNames.KeyboardIcon)
export const LanguagesIcon = getIcon(materialSymbolNames.LanguagesIcon)
export const LayoutGridIcon = getIcon(materialSymbolNames.LayoutGridIcon)
export const LayoutIcon = getIcon(materialSymbolNames.LayoutIcon)
export const LifeBuoyIcon = getIcon(materialSymbolNames.LifeBuoyIcon)
export const Link2Icon = getIcon(materialSymbolNames.Link2Icon)
export const ListFilterIcon = getIcon(materialSymbolNames.ListFilterIcon)
export const ListIcon = getIcon(materialSymbolNames.ListIcon)
export const LoaderIcon = getIcon(materialSymbolNames.LoaderIcon)
export const LogOut = getIcon(materialSymbolNames.LogOut)
export const LogOutIcon = getIcon(materialSymbolNames.LogOutIcon)
export const MailCheckIcon = getIcon(materialSymbolNames.MailCheckIcon)
export const MailIcon = getIcon(materialSymbolNames.MailIcon)
export const Map = getIcon(materialSymbolNames.Map)
export const MapIcon = getIcon(materialSymbolNames.MapIcon)
export const MaximizeIcon = getIcon(materialSymbolNames.MaximizeIcon)
export const MessageSquareIcon = getIcon(materialSymbolNames.MessageSquareIcon)
export const MicIcon = getIcon(materialSymbolNames.MicIcon)
export const MinimizeIcon = getIcon(materialSymbolNames.MinimizeIcon)
export const Minus = getIcon(materialSymbolNames.Minus)
export const MinusIcon = getIcon(materialSymbolNames.MinusIcon)
export const MonitorIcon = getIcon(materialSymbolNames.MonitorIcon)
export const MoonIcon = getIcon(materialSymbolNames.MoonIcon)
export const MoreHorizontal = getIcon(materialSymbolNames.MoreHorizontal)
export const MoreHorizontalIcon = getIcon(
  materialSymbolNames.MoreHorizontalIcon
)
export const PaletteIcon = getIcon(materialSymbolNames.PaletteIcon)
export const PanelLeftCloseIcon = getIcon(
  materialSymbolNames.PanelLeftCloseIcon
)
export const PanelLeftOpenIcon = getIcon(materialSymbolNames.PanelLeftOpenIcon)
export const PencilIcon = getIcon(materialSymbolNames.PencilIcon)
export const PieChart = getIcon(materialSymbolNames.PieChart)
export const PieChartIcon = getIcon(materialSymbolNames.PieChartIcon)
export const Plus = getIcon(materialSymbolNames.Plus)
export const PlusIcon = getIcon(materialSymbolNames.PlusIcon)
export const RadioIcon = getIcon(materialSymbolNames.RadioIcon)
export const RefreshCcwIcon = getIcon(materialSymbolNames.RefreshCcwIcon)
export const RefreshCwIcon = getIcon(materialSymbolNames.RefreshCwIcon)
export const RotateCwIcon = getIcon(materialSymbolNames.RotateCwIcon)
export const SaveIcon = getIcon(materialSymbolNames.SaveIcon)
export const ScissorsIcon = getIcon(materialSymbolNames.ScissorsIcon)
export const Search = getIcon(materialSymbolNames.Search)
export const SearchIcon = getIcon(materialSymbolNames.SearchIcon)
export const SendIcon = getIcon(materialSymbolNames.SendIcon)
export const Settings = getIcon(materialSymbolNames.Settings)
export const Settings2 = getIcon(materialSymbolNames.Settings2)
export const SettingsIcon = getIcon(materialSymbolNames.SettingsIcon)
export const ShareIcon = getIcon(materialSymbolNames.ShareIcon)
export const ShieldAlertIcon = getIcon(materialSymbolNames.ShieldAlertIcon)
export const ShieldIcon = getIcon(materialSymbolNames.ShieldIcon)
export const Smile = getIcon(materialSymbolNames.Smile)
export const SmileIcon = getIcon(materialSymbolNames.SmileIcon)
export const Sparkles = getIcon(materialSymbolNames.Sparkles)
export const SparklesIcon = getIcon(materialSymbolNames.SparklesIcon)
export const SquareTerminal = getIcon(materialSymbolNames.SquareTerminal)
export const StarIcon = getIcon(materialSymbolNames.StarIcon)
export const SunIcon = getIcon(materialSymbolNames.SunIcon)
export const TagIcon = getIcon(materialSymbolNames.TagIcon)
export const Trash2 = getIcon(materialSymbolNames.Trash2)
export const Trash2Icon = getIcon(materialSymbolNames.Trash2Icon)
export const TrashIcon = getIcon(materialSymbolNames.TrashIcon)
export const TriangleAlertIcon = getIcon(materialSymbolNames.TriangleAlertIcon)
export const Underline = getIcon(materialSymbolNames.Underline)
export const UnderlineIcon = getIcon(materialSymbolNames.UnderlineIcon)
export const User = getIcon(materialSymbolNames.User)
export const UserIcon = getIcon(materialSymbolNames.UserIcon)
export const UserRoundXIcon = getIcon(materialSymbolNames.UserRoundXIcon)
export const VolumeOffIcon = getIcon(materialSymbolNames.VolumeOffIcon)
export const WalletIcon = getIcon(materialSymbolNames.WalletIcon)
export const ZoomInIcon = getIcon(materialSymbolNames.ZoomInIcon)
export const ZoomOutIcon = getIcon(materialSymbolNames.ZoomOutIcon)
