// Auto-generated by scripts/build-source-manifest.ts
// Do not edit manually

import type { PageMetadata, PageTreeNode } from "./types"

export const pagesManifest: PageMetadata[] = [
  {
    "slug": [
      "blocks"
    ],
    "url": "/docs/blocks",
    "title": "Blocks",
    "description": "Contribute components to the blocks library."
  },
  {
    "slug": [
      "changelog"
    ],
    "url": "/docs/changelog",
    "title": "Changelog",
    "description": "Latest updates and announcements."
  },
  {
    "slug": [
      "cli"
    ],
    "url": "/docs/cli",
    "title": "shadcn",
    "description": "Use the shadcn CLI to add components to your project."
  },
  {
    "slug": [
      "components-json"
    ],
    "url": "/docs/components-json",
    "title": "components.json",
    "description": "Configuration for your project."
  },
  {
    "slug": [
      "directory"
    ],
    "url": "/docs/directory",
    "title": "Registry Directory",
    "description": "Discover community registries for shadcn/ui components and blocks."
  },
  {
    "slug": [
      "figma"
    ],
    "url": "/docs/figma",
    "title": "Figma",
    "description": "Every component recreated in Figma. With customizable props, typography and icons."
  },
  {
    "slug": [],
    "url": "/docs",
    "title": "Introduction",
    "description": "shadcn/ui is a set of beautifully-designed, accessible components and a code distribution platform. Works with your favorite frameworks and AI models. Open Source. Open Code."
  },
  {
    "slug": [
      "javascript"
    ],
    "url": "/docs/javascript",
    "title": "JavaScript",
    "description": "How to use shadcn/ui with JavaScript"
  },
  {
    "slug": [
      "legacy"
    ],
    "url": "/docs/legacy",
    "title": "Legacy Docs",
    "description": "View the legacy docs for shadcn/ui and Tailwind v3."
  },
  {
    "slug": [
      "mcp"
    ],
    "url": "/docs/mcp",
    "title": "MCP Server",
    "description": "Use the shadcn MCP server to browse, search, and install components from registries."
  },
  {
    "slug": [
      "monorepo"
    ],
    "url": "/docs/monorepo",
    "title": "Monorepo",
    "description": "Using shadcn/ui components and CLI in a monorepo."
  },
  {
    "slug": [
      "react-19"
    ],
    "url": "/docs/react-19",
    "title": "Next.js 15 + React 19",
    "description": "Using shadcn/ui with Next.js 15 and React 19."
  },
  {
    "slug": [
      "tailwind-v4"
    ],
    "url": "/docs/tailwind-v4",
    "title": "Tailwind v4",
    "description": "How to use shadcn/ui with Tailwind v4 and React 19."
  },
  {
    "slug": [
      "theming"
    ],
    "url": "/docs/theming",
    "title": "Theming",
    "description": "Using CSS Variables and color utilities for theming."
  },
  {
    "slug": [
      "v0"
    ],
    "url": "/docs/v0",
    "title": "Open in v0",
    "description": "Open components in v0 for customization."
  },
  {
    "slug": [
      "components",
      "accordion"
    ],
    "url": "/docs/components/accordion",
    "title": "Accordion",
    "description": "A vertically stacked set of interactive headings that each reveal a section of content.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/accordion",
      "api": "https://www.radix-ui.com/docs/primitives/components/accordion#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "alert-dialog"
    ],
    "url": "/docs/components/alert-dialog",
    "title": "Alert Dialog",
    "description": "A modal dialog that interrupts the user with important content and expects a response.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/alert-dialog",
      "api": "https://www.radix-ui.com/docs/primitives/components/alert-dialog#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "alert"
    ],
    "url": "/docs/components/alert",
    "title": "Alert",
    "description": "Displays a callout for user attention.",
    "component": true
  },
  {
    "slug": [
      "components",
      "aspect-ratio"
    ],
    "url": "/docs/components/aspect-ratio",
    "title": "Aspect Ratio",
    "description": "Displays content within a desired ratio.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/aspect-ratio",
      "api": "https://www.radix-ui.com/docs/primitives/components/aspect-ratio#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "avatar"
    ],
    "url": "/docs/components/avatar",
    "title": "Avatar",
    "description": "An image element with a fallback for representing the user.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/avatar",
      "api": "https://www.radix-ui.com/docs/primitives/components/avatar#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "badge"
    ],
    "url": "/docs/components/badge",
    "title": "Badge",
    "description": "Displays a badge or a component that looks like a badge.",
    "component": true
  },
  {
    "slug": [
      "components",
      "breadcrumb"
    ],
    "url": "/docs/components/breadcrumb",
    "title": "Breadcrumb",
    "description": "Displays the path to the current resource using a hierarchy of links.",
    "component": true
  },
  {
    "slug": [
      "components",
      "button-group"
    ],
    "url": "/docs/components/button-group",
    "title": "Button Group",
    "description": "A container that groups related buttons together with consistent styling.",
    "component": true
  },
  {
    "slug": [
      "components",
      "button"
    ],
    "url": "/docs/components/button",
    "title": "Button",
    "description": "Displays a button or a component that looks like a button.",
    "component": true
  },
  {
    "slug": [
      "components",
      "calendar"
    ],
    "url": "/docs/components/calendar",
    "title": "Calendar",
    "description": "A date field component that allows users to enter and edit date.",
    "links": {
      "doc": "https://react-day-picker.js.org"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "card"
    ],
    "url": "/docs/components/card",
    "title": "Card",
    "description": "Displays a card with header, content, and footer.",
    "component": true
  },
  {
    "slug": [
      "components",
      "carousel"
    ],
    "url": "/docs/components/carousel",
    "title": "Carousel",
    "description": "A carousel with motion and swipe built using Embla.",
    "links": {
      "doc": "https://www.embla-carousel.com/get-started/react",
      "api": "https://www.embla-carousel.com/api"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "chart"
    ],
    "url": "/docs/components/chart",
    "title": "Chart",
    "description": "Beautiful charts. Built using Recharts. Copy and paste into your apps.",
    "component": true
  },
  {
    "slug": [
      "components",
      "checkbox"
    ],
    "url": "/docs/components/checkbox",
    "title": "Checkbox",
    "description": "A control that allows the user to toggle between checked and not checked.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/checkbox",
      "api": "https://www.radix-ui.com/docs/primitives/components/checkbox#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "collapsible"
    ],
    "url": "/docs/components/collapsible",
    "title": "Collapsible",
    "description": "An interactive component which expands/collapses a panel.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/collapsible",
      "api": "https://www.radix-ui.com/docs/primitives/components/collapsible#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "combobox"
    ],
    "url": "/docs/components/combobox",
    "title": "Combobox",
    "description": "Autocomplete input and command palette with a list of suggestions.",
    "component": true
  },
  {
    "slug": [
      "components",
      "command"
    ],
    "url": "/docs/components/command",
    "title": "Command",
    "description": "Fast, composable, unstyled command menu for React.",
    "links": {
      "doc": "https://cmdk.paco.me"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "context-menu"
    ],
    "url": "/docs/components/context-menu",
    "title": "Context Menu",
    "description": "Displays a menu to the user — such as a set of actions or functions — triggered by a button.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/context-menu",
      "api": "https://www.radix-ui.com/docs/primitives/components/context-menu#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "data-table"
    ],
    "url": "/docs/components/data-table",
    "title": "Data Table",
    "description": "Powerful table and datagrids built using TanStack Table.",
    "links": {
      "doc": "https://tanstack.com/table/v8/docs/introduction"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "date-picker"
    ],
    "url": "/docs/components/date-picker",
    "title": "Date Picker",
    "description": "A date picker component with range and presets.",
    "component": true
  },
  {
    "slug": [
      "components",
      "dialog"
    ],
    "url": "/docs/components/dialog",
    "title": "Dialog",
    "description": "A window overlaid on either the primary window or another dialog window, rendering the content underneath inert.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/dialog",
      "api": "https://www.radix-ui.com/docs/primitives/components/dialog#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "drawer"
    ],
    "url": "/docs/components/drawer",
    "title": "Drawer",
    "description": "A drawer component for React.",
    "links": {
      "doc": "https://vaul.emilkowal.ski/getting-started"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "dropdown-menu"
    ],
    "url": "/docs/components/dropdown-menu",
    "title": "Dropdown Menu",
    "description": "Displays a menu to the user — such as a set of actions or functions — triggered by a button.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/dropdown-menu",
      "api": "https://www.radix-ui.com/docs/primitives/components/dropdown-menu#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "empty"
    ],
    "url": "/docs/components/empty",
    "title": "Empty",
    "description": "Use the Empty component to display an empty state.",
    "component": true
  },
  {
    "slug": [
      "components",
      "field"
    ],
    "url": "/docs/components/field",
    "title": "Field",
    "description": "Combine labels, controls, and help text to compose accessible form fields and grouped inputs.",
    "component": true
  },
  {
    "slug": [
      "components",
      "form"
    ],
    "url": "/docs/components/form",
    "title": "Form",
    "description": "Building forms with React Hook Form and Zod.",
    "links": {
      "doc": "https://react-hook-form.com"
    }
  },
  {
    "slug": [
      "components",
      "hover-card"
    ],
    "url": "/docs/components/hover-card",
    "title": "Hover Card",
    "description": "For sighted users to preview content available behind a link.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/hover-card",
      "api": "https://www.radix-ui.com/docs/primitives/components/hover-card#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components"
    ],
    "url": "/docs/components",
    "title": "Components",
    "description": "Here you can find all the components available in the library. We are working on adding more components."
  },
  {
    "slug": [
      "components",
      "input-group"
    ],
    "url": "/docs/components/input-group",
    "title": "Input Group",
    "description": "Display additional information or actions to an input or textarea.",
    "component": true
  },
  {
    "slug": [
      "components",
      "input-otp"
    ],
    "url": "/docs/components/input-otp",
    "title": "Input OTP",
    "description": "Accessible one-time password component with copy paste functionality.",
    "links": {
      "doc": "https://input-otp.rodz.dev"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "input"
    ],
    "url": "/docs/components/input",
    "title": "Input",
    "description": "Displays a form input field or a component that looks like an input field.",
    "component": true
  },
  {
    "slug": [
      "components",
      "item"
    ],
    "url": "/docs/components/item",
    "title": "Item",
    "description": "A versatile component that you can use to display any content.",
    "component": true
  },
  {
    "slug": [
      "components",
      "kbd"
    ],
    "url": "/docs/components/kbd",
    "title": "Kbd",
    "description": "Used to display textual user input from keyboard.",
    "component": true
  },
  {
    "slug": [
      "components",
      "label"
    ],
    "url": "/docs/components/label",
    "title": "Label",
    "description": "Renders an accessible label associated with controls.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/label",
      "api": "https://www.radix-ui.com/docs/primitives/components/label#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "menubar"
    ],
    "url": "/docs/components/menubar",
    "title": "Menubar",
    "description": "A visually persistent menu common in desktop applications that provides quick access to a consistent set of commands.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/menubar",
      "api": "https://www.radix-ui.com/docs/primitives/components/menubar#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "native-select"
    ],
    "url": "/docs/components/native-select",
    "title": "Native Select",
    "description": "A styled native HTML select element with consistent design system integration.",
    "component": true
  },
  {
    "slug": [
      "components",
      "navigation-menu"
    ],
    "url": "/docs/components/navigation-menu",
    "title": "Navigation Menu",
    "description": "A collection of links for navigating websites.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/navigation-menu",
      "api": "https://www.radix-ui.com/docs/primitives/components/navigation-menu#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "pagination"
    ],
    "url": "/docs/components/pagination",
    "title": "Pagination",
    "description": "Pagination with page navigation, next and previous links.",
    "component": true
  },
  {
    "slug": [
      "components",
      "popover"
    ],
    "url": "/docs/components/popover",
    "title": "Popover",
    "description": "Displays rich content in a portal, triggered by a button.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/popover",
      "api": "https://www.radix-ui.com/docs/primitives/components/popover#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "progress"
    ],
    "url": "/docs/components/progress",
    "title": "Progress",
    "description": "Displays an indicator showing the completion progress of a task, typically displayed as a progress bar.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/progress",
      "api": "https://www.radix-ui.com/docs/primitives/components/progress#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "radio-group"
    ],
    "url": "/docs/components/radio-group",
    "title": "Radio Group",
    "description": "A set of checkable buttons—known as radio buttons—where no more than one of the buttons can be checked at a time.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/radio-group",
      "api": "https://www.radix-ui.com/docs/primitives/components/radio-group#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "resizable"
    ],
    "url": "/docs/components/resizable",
    "title": "Resizable",
    "description": "Accessible resizable panel groups and layouts with keyboard support.",
    "links": {
      "doc": "https://github.com/bvaughn/react-resizable-panels",
      "api": "https://github.com/bvaughn/react-resizable-panels/tree/main/packages/react-resizable-panels"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "scroll-area"
    ],
    "url": "/docs/components/scroll-area",
    "title": "Scroll Area",
    "description": "Augments native scroll functionality for custom, cross-browser styling.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/scroll-area",
      "api": "https://www.radix-ui.com/docs/primitives/components/scroll-area#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "select"
    ],
    "url": "/docs/components/select",
    "title": "Select",
    "description": "Displays a list of options for the user to pick from—triggered by a button.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/select",
      "api": "https://www.radix-ui.com/docs/primitives/components/select#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "separator"
    ],
    "url": "/docs/components/separator",
    "title": "Separator",
    "description": "Visually or semantically separates content.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/separator",
      "api": "https://www.radix-ui.com/docs/primitives/components/separator#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "sheet"
    ],
    "url": "/docs/components/sheet",
    "title": "Sheet",
    "description": "Extends the Dialog component to display content that complements the main content of the screen.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/dialog",
      "api": "https://www.radix-ui.com/docs/primitives/components/dialog#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "sidebar"
    ],
    "url": "/docs/components/sidebar",
    "title": "Sidebar",
    "description": "A composable, themeable and customizable sidebar component.",
    "component": true
  },
  {
    "slug": [
      "components",
      "skeleton"
    ],
    "url": "/docs/components/skeleton",
    "title": "Skeleton",
    "description": "Use to show a placeholder while content is loading.",
    "component": true
  },
  {
    "slug": [
      "components",
      "slider"
    ],
    "url": "/docs/components/slider",
    "title": "Slider",
    "description": "An input where the user selects a value from within a given range.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/slider",
      "api": "https://www.radix-ui.com/docs/primitives/components/slider#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "sonner"
    ],
    "url": "/docs/components/sonner",
    "title": "Sonner",
    "description": "An opinionated toast component for React.",
    "links": {
      "doc": "https://sonner.emilkowal.ski"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "spinner"
    ],
    "url": "/docs/components/spinner",
    "title": "Spinner",
    "description": "An indicator that can be used to show a loading state.",
    "component": true
  },
  {
    "slug": [
      "components",
      "switch"
    ],
    "url": "/docs/components/switch",
    "title": "Switch",
    "description": "A control that allows the user to toggle between checked and not checked.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/switch",
      "api": "https://www.radix-ui.com/docs/primitives/components/switch#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "table"
    ],
    "url": "/docs/components/table",
    "title": "Table",
    "description": "A responsive table component.",
    "component": true
  },
  {
    "slug": [
      "components",
      "tabs"
    ],
    "url": "/docs/components/tabs",
    "title": "Tabs",
    "description": "A set of layered sections of content—known as tab panels—that are displayed one at a time.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/tabs",
      "api": "https://www.radix-ui.com/docs/primitives/components/tabs#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "textarea"
    ],
    "url": "/docs/components/textarea",
    "title": "Textarea",
    "description": "Displays a form textarea or a component that looks like a textarea.",
    "component": true
  },
  {
    "slug": [
      "components",
      "toast"
    ],
    "url": "/docs/components/toast",
    "title": "Toast",
    "description": "A succinct message that is displayed temporarily.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/toast",
      "api": "https://www.radix-ui.com/docs/primitives/components/toast#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "toggle-group"
    ],
    "url": "/docs/components/toggle-group",
    "title": "Toggle Group",
    "description": "A set of two-state buttons that can be toggled on or off.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/toggle-group",
      "api": "https://www.radix-ui.com/docs/primitives/components/toggle-group#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "toggle"
    ],
    "url": "/docs/components/toggle",
    "title": "Toggle",
    "description": "A two-state button that can be either on or off.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/toggle",
      "api": "https://www.radix-ui.com/docs/primitives/components/toggle#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "tooltip"
    ],
    "url": "/docs/components/tooltip",
    "title": "Tooltip",
    "description": "A popup that displays information related to an element when the element receives keyboard focus or the mouse hovers over it.",
    "links": {
      "doc": "https://www.radix-ui.com/docs/primitives/components/tooltip",
      "api": "https://www.radix-ui.com/docs/primitives/components/tooltip#api-reference"
    },
    "component": true
  },
  {
    "slug": [
      "components",
      "typography"
    ],
    "url": "/docs/components/typography",
    "title": "Typography",
    "description": "Styles for headings, paragraphs, lists...etc",
    "component": true
  },
  {
    "slug": [
      "dark-mode",
      "astro"
    ],
    "url": "/docs/dark-mode/astro",
    "title": "Astro",
    "description": "Adding dark mode to your astro app."
  },
  {
    "slug": [
      "dark-mode"
    ],
    "url": "/docs/dark-mode",
    "title": "Dark Mode",
    "description": "Adding dark mode to your site."
  },
  {
    "slug": [
      "dark-mode",
      "next"
    ],
    "url": "/docs/dark-mode/next",
    "title": "Next.js",
    "description": "Adding dark mode to your next app."
  },
  {
    "slug": [
      "dark-mode",
      "remix"
    ],
    "url": "/docs/dark-mode/remix",
    "title": "Remix",
    "description": "Adding dark mode to your remix app."
  },
  {
    "slug": [
      "dark-mode",
      "vite"
    ],
    "url": "/docs/dark-mode/vite",
    "title": "Vite",
    "description": "Adding dark mode to your vite app."
  },
  {
    "slug": [
      "forms"
    ],
    "url": "/docs/forms",
    "title": "Forms",
    "description": "Build forms with React and shadcn/ui."
  },
  {
    "slug": [
      "forms",
      "next"
    ],
    "url": "/docs/forms/next",
    "title": "Next.js",
    "description": "Build forms in React using useActionState and Server Actions."
  },
  {
    "slug": [
      "forms",
      "react-hook-form"
    ],
    "url": "/docs/forms/react-hook-form",
    "title": "React Hook Form",
    "description": "Build forms in React using React Hook Form and Zod.",
    "links": {
      "doc": "https://react-hook-form.com"
    }
  },
  {
    "slug": [
      "forms",
      "tanstack-form"
    ],
    "url": "/docs/forms/tanstack-form",
    "title": "TanStack Form",
    "description": "Build forms in React using TanStack Form and Zod.",
    "links": {
      "doc": "https://tanstack.com/form"
    }
  },
  {
    "slug": [
      "installation",
      "astro"
    ],
    "url": "/docs/installation/astro",
    "title": "Astro",
    "description": "Install and configure shadcn/ui for Astro"
  },
  {
    "slug": [
      "installation",
      "gatsby"
    ],
    "url": "/docs/installation/gatsby",
    "title": "Gatsby",
    "description": "Install and configure Gatsby."
  },
  {
    "slug": [
      "installation"
    ],
    "url": "/docs/installation",
    "title": "Installation",
    "description": "How to install dependencies and structure your app."
  },
  {
    "slug": [
      "installation",
      "laravel"
    ],
    "url": "/docs/installation/laravel",
    "title": "Laravel",
    "description": "Install and configure shadcn/ui for Laravel"
  },
  {
    "slug": [
      "installation",
      "manual"
    ],
    "url": "/docs/installation/manual",
    "title": "Manual Installation",
    "description": "Add dependencies to your project manually."
  },
  {
    "slug": [
      "installation",
      "next"
    ],
    "url": "/docs/installation/next",
    "title": "Next.js",
    "description": "Install and configure shadcn/ui for Next.js."
  },
  {
    "slug": [
      "installation",
      "react-router"
    ],
    "url": "/docs/installation/react-router",
    "title": "React Router",
    "description": "Install and configure shadcn/ui for React Router."
  },
  {
    "slug": [
      "installation",
      "remix"
    ],
    "url": "/docs/installation/remix",
    "title": "Remix",
    "description": "Install and configure shadcn/ui for Remix."
  },
  {
    "slug": [
      "installation",
      "tanstack-router"
    ],
    "url": "/docs/installation/tanstack-router",
    "title": "TanStack Router",
    "description": "Install and configure shadcn/ui for TanStack Router."
  },
  {
    "slug": [
      "installation",
      "tanstack"
    ],
    "url": "/docs/installation/tanstack",
    "title": "TanStack Start",
    "description": "Install and configure shadcn/ui for TanStack Start."
  },
  {
    "slug": [
      "installation",
      "vite"
    ],
    "url": "/docs/installation/vite",
    "title": "Vite",
    "description": "Install and configure shadcn/ui for Vite."
  },
  {
    "slug": [
      "registry",
      "authentication"
    ],
    "url": "/docs/registry/authentication",
    "title": "Authentication",
    "description": "Secure your registry with authentication for private and personalized components."
  },
  {
    "slug": [
      "registry",
      "examples"
    ],
    "url": "/docs/registry/examples",
    "title": "Examples",
    "description": "Examples of registry items: styles, components, css vars, etc."
  },
  {
    "slug": [
      "registry",
      "faq"
    ],
    "url": "/docs/registry/faq",
    "title": "FAQ",
    "description": "Frequently asked questions about running a registry."
  },
  {
    "slug": [
      "registry",
      "getting-started"
    ],
    "url": "/docs/registry/getting-started",
    "title": "Getting Started",
    "description": "Learn how to get setup and run your own component registry."
  },
  {
    "slug": [
      "registry"
    ],
    "url": "/docs/registry",
    "title": "Introduction",
    "description": "Run your own code registry."
  },
  {
    "slug": [
      "registry",
      "mcp"
    ],
    "url": "/docs/registry/mcp",
    "title": "MCP Server",
    "description": "MCP support for registry developers"
  },
  {
    "slug": [
      "registry",
      "namespace"
    ],
    "url": "/docs/registry/namespace",
    "title": "Namespaces",
    "description": "Configure and use multiple resource registries with namespace support."
  },
  {
    "slug": [
      "registry",
      "open-in-v0"
    ],
    "url": "/docs/registry/open-in-v0",
    "title": "Open in v0",
    "description": "Integrate your registry with Open in v0."
  },
  {
    "slug": [
      "registry",
      "registry-index"
    ],
    "url": "/docs/registry/registry-index",
    "title": "Add a Registry",
    "description": "Open Source Registry Index"
  },
  {
    "slug": [
      "registry",
      "registry-item-json"
    ],
    "url": "/docs/registry/registry-item-json",
    "title": "registry-item.json",
    "description": "Specification for registry items."
  },
  {
    "slug": [
      "registry",
      "registry-json"
    ],
    "url": "/docs/registry/registry-json",
    "title": "registry.json",
    "description": "Schema for running your own component registry."
  }
]

export const pageTree: PageTreeNode = {
  "type": "folder",
  "name": "Documentation",
  "children": [
    {
      "type": "folder",
      "name": "Get Started",
      "url": "/docs",
      "$id": "(root)",
      "children": [
        {
          "type": "page",
          "name": "Introduction",
          "url": "/docs",
          "$id": "index",
          "external": false
        },
        {
          "type": "page",
          "name": "Installation",
          "url": "/docs/installation",
          "$id": "installation",
          "external": false
        },
        {
          "type": "page",
          "name": "components.json",
          "url": "/docs/components-json",
          "$id": "components-json",
          "external": false
        },
        {
          "type": "page",
          "name": "Theming",
          "url": "/docs/theming",
          "$id": "theming",
          "external": false
        },
        {
          "type": "page",
          "name": "Dark Mode",
          "url": "/docs/dark-mode",
          "$id": "dark-mode",
          "external": false
        },
        {
          "type": "page",
          "name": "CLI",
          "url": "/docs/cli",
          "$id": "cli",
          "external": false
        },
        {
          "type": "page",
          "name": "Monorepo",
          "url": "/docs/monorepo",
          "$id": "monorepo",
          "external": false
        },
        {
          "type": "page",
          "name": "Open in v0",
          "url": "/docs/v0",
          "$id": "v0",
          "external": false
        },
        {
          "type": "page",
          "name": "JavaScript",
          "url": "/docs/javascript",
          "$id": "javascript",
          "external": false
        },
        {
          "type": "page",
          "name": "Blocks",
          "url": "/docs/blocks",
          "$id": "blocks",
          "external": false
        },
        {
          "type": "page",
          "name": "Figma",
          "url": "/docs/figma",
          "$id": "figma",
          "external": false
        },
        {
          "type": "page",
          "name": "Changelog",
          "url": "/docs/changelog",
          "$id": "changelog",
          "external": false
        },
        {
          "type": "page",
          "name": "llms.txt",
          "url": "/llms.txt",
          "$id": "llms.txt",
          "external": false
        },
        {
          "type": "page",
          "name": "Legacy Docs",
          "url": "/docs/legacy",
          "$id": "legacy",
          "external": false
        }
      ]
    },
    {
      "type": "folder",
      "name": "Components",
      "url": "/docs/components",
      "$id": "components",
      "children": [
        {
          "type": "page",
          "name": "Accordion",
          "url": "/docs/components/accordion",
          "$id": "accordion",
          "external": false
        },
        {
          "type": "page",
          "name": "Alert",
          "url": "/docs/components/alert",
          "$id": "alert",
          "external": false
        },
        {
          "type": "page",
          "name": "Alert Dialog",
          "url": "/docs/components/alert-dialog",
          "$id": "alert-dialog",
          "external": false
        },
        {
          "type": "page",
          "name": "Aspect Ratio",
          "url": "/docs/components/aspect-ratio",
          "$id": "aspect-ratio",
          "external": false
        },
        {
          "type": "page",
          "name": "Avatar",
          "url": "/docs/components/avatar",
          "$id": "avatar",
          "external": false
        },
        {
          "type": "page",
          "name": "Badge",
          "url": "/docs/components/badge",
          "$id": "badge",
          "external": false
        },
        {
          "type": "page",
          "name": "Breadcrumb",
          "url": "/docs/components/breadcrumb",
          "$id": "breadcrumb",
          "external": false
        },
        {
          "type": "page",
          "name": "Button",
          "url": "/docs/components/button",
          "$id": "button",
          "external": false
        },
        {
          "type": "page",
          "name": "Button Group",
          "url": "/docs/components/button-group",
          "$id": "button-group",
          "external": false
        },
        {
          "type": "page",
          "name": "Calendar",
          "url": "/docs/components/calendar",
          "$id": "calendar",
          "external": false
        },
        {
          "type": "page",
          "name": "Card",
          "url": "/docs/components/card",
          "$id": "card",
          "external": false
        },
        {
          "type": "page",
          "name": "Carousel",
          "url": "/docs/components/carousel",
          "$id": "carousel",
          "external": false
        },
        {
          "type": "page",
          "name": "Chart",
          "url": "/docs/components/chart",
          "$id": "chart",
          "external": false
        },
        {
          "type": "page",
          "name": "Checkbox",
          "url": "/docs/components/checkbox",
          "$id": "checkbox",
          "external": false
        },
        {
          "type": "page",
          "name": "Collapsible",
          "url": "/docs/components/collapsible",
          "$id": "collapsible",
          "external": false
        },
        {
          "type": "page",
          "name": "Combobox",
          "url": "/docs/components/combobox",
          "$id": "combobox",
          "external": false
        },
        {
          "type": "page",
          "name": "Command",
          "url": "/docs/components/command",
          "$id": "command",
          "external": false
        },
        {
          "type": "page",
          "name": "Context Menu",
          "url": "/docs/components/context-menu",
          "$id": "context-menu",
          "external": false
        },
        {
          "type": "page",
          "name": "Data Table",
          "url": "/docs/components/data-table",
          "$id": "data-table",
          "external": false
        },
        {
          "type": "page",
          "name": "Date Picker",
          "url": "/docs/components/date-picker",
          "$id": "date-picker",
          "external": false
        },
        {
          "type": "page",
          "name": "Dialog",
          "url": "/docs/components/dialog",
          "$id": "dialog",
          "external": false
        },
        {
          "type": "page",
          "name": "Drawer",
          "url": "/docs/components/drawer",
          "$id": "drawer",
          "external": false
        },
        {
          "type": "page",
          "name": "Dropdown Menu",
          "url": "/docs/components/dropdown-menu",
          "$id": "dropdown-menu",
          "external": false
        },
        {
          "type": "page",
          "name": "Empty",
          "url": "/docs/components/empty",
          "$id": "empty",
          "external": false
        },
        {
          "type": "page",
          "name": "Field",
          "url": "/docs/components/field",
          "$id": "field",
          "external": false
        },
        {
          "type": "page",
          "name": "Form",
          "url": "/docs/components/form",
          "$id": "form",
          "external": false
        },
        {
          "type": "page",
          "name": "Hover Card",
          "url": "/docs/components/hover-card",
          "$id": "hover-card",
          "external": false
        },
        {
          "type": "page",
          "name": "Input",
          "url": "/docs/components/input",
          "$id": "input",
          "external": false
        },
        {
          "type": "page",
          "name": "Input Group",
          "url": "/docs/components/input-group",
          "$id": "input-group",
          "external": false
        },
        {
          "type": "page",
          "name": "Input OTP",
          "url": "/docs/components/input-otp",
          "$id": "input-otp",
          "external": false
        },
        {
          "type": "page",
          "name": "Item",
          "url": "/docs/components/item",
          "$id": "item",
          "external": false
        },
        {
          "type": "page",
          "name": "Kbd",
          "url": "/docs/components/kbd",
          "$id": "kbd",
          "external": false
        },
        {
          "type": "page",
          "name": "Label",
          "url": "/docs/components/label",
          "$id": "label",
          "external": false
        },
        {
          "type": "page",
          "name": "Menubar",
          "url": "/docs/components/menubar",
          "$id": "menubar",
          "external": false
        },
        {
          "type": "page",
          "name": "Native Select",
          "url": "/docs/components/native-select",
          "$id": "native-select",
          "external": false
        },
        {
          "type": "page",
          "name": "Navigation Menu",
          "url": "/docs/components/navigation-menu",
          "$id": "navigation-menu",
          "external": false
        },
        {
          "type": "page",
          "name": "Pagination",
          "url": "/docs/components/pagination",
          "$id": "pagination",
          "external": false
        },
        {
          "type": "page",
          "name": "Popover",
          "url": "/docs/components/popover",
          "$id": "popover",
          "external": false
        },
        {
          "type": "page",
          "name": "Progress",
          "url": "/docs/components/progress",
          "$id": "progress",
          "external": false
        },
        {
          "type": "page",
          "name": "Radio Group",
          "url": "/docs/components/radio-group",
          "$id": "radio-group",
          "external": false
        },
        {
          "type": "page",
          "name": "Resizable",
          "url": "/docs/components/resizable",
          "$id": "resizable",
          "external": false
        },
        {
          "type": "page",
          "name": "Scroll Area",
          "url": "/docs/components/scroll-area",
          "$id": "scroll-area",
          "external": false
        },
        {
          "type": "page",
          "name": "Select",
          "url": "/docs/components/select",
          "$id": "select",
          "external": false
        },
        {
          "type": "page",
          "name": "Separator",
          "url": "/docs/components/separator",
          "$id": "separator",
          "external": false
        },
        {
          "type": "page",
          "name": "Sheet",
          "url": "/docs/components/sheet",
          "$id": "sheet",
          "external": false
        },
        {
          "type": "page",
          "name": "Sidebar",
          "url": "/docs/components/sidebar",
          "$id": "sidebar",
          "external": false
        },
        {
          "type": "page",
          "name": "Skeleton",
          "url": "/docs/components/skeleton",
          "$id": "skeleton",
          "external": false
        },
        {
          "type": "page",
          "name": "Slider",
          "url": "/docs/components/slider",
          "$id": "slider",
          "external": false
        },
        {
          "type": "page",
          "name": "Sonner",
          "url": "/docs/components/sonner",
          "$id": "sonner",
          "external": false
        },
        {
          "type": "page",
          "name": "Spinner",
          "url": "/docs/components/spinner",
          "$id": "spinner",
          "external": false
        },
        {
          "type": "page",
          "name": "Switch",
          "url": "/docs/components/switch",
          "$id": "switch",
          "external": false
        },
        {
          "type": "page",
          "name": "Table",
          "url": "/docs/components/table",
          "$id": "table",
          "external": false
        },
        {
          "type": "page",
          "name": "Tabs",
          "url": "/docs/components/tabs",
          "$id": "tabs",
          "external": false
        },
        {
          "type": "page",
          "name": "Textarea",
          "url": "/docs/components/textarea",
          "$id": "textarea",
          "external": false
        },
        {
          "type": "page",
          "name": "Toast",
          "url": "/docs/components/toast",
          "$id": "toast",
          "external": false
        },
        {
          "type": "page",
          "name": "Toggle",
          "url": "/docs/components/toggle",
          "$id": "toggle",
          "external": false
        },
        {
          "type": "page",
          "name": "Toggle Group",
          "url": "/docs/components/toggle-group",
          "$id": "toggle-group",
          "external": false
        },
        {
          "type": "page",
          "name": "Tooltip",
          "url": "/docs/components/tooltip",
          "$id": "tooltip",
          "external": false
        },
        {
          "type": "page",
          "name": "Typography",
          "url": "/docs/components/typography",
          "$id": "typography",
          "external": false
        }
      ]
    },
    {
      "type": "folder",
      "name": "forms",
      "url": "/docs/forms",
      "$id": "forms",
      "children": [
        {
          "type": "page",
          "name": "React Hook Form",
          "url": "/docs/forms/react-hook-form",
          "$id": "react-hook-form",
          "external": false
        },
        {
          "type": "page",
          "name": "TanStack Form",
          "url": "/docs/forms/tanstack-form",
          "$id": "tanstack-form",
          "external": false
        }
      ]
    },
    {
      "type": "folder",
      "name": "installation",
      "url": "/docs/installation",
      "$id": "installation",
      "children": [
        {
          "type": "page",
          "name": "Next.js",
          "url": "/docs/installation/next",
          "$id": "next",
          "external": false
        },
        {
          "type": "page",
          "name": "Vite",
          "url": "/docs/installation/vite",
          "$id": "vite",
          "external": false
        },
        {
          "type": "page",
          "name": "Laravel",
          "url": "/docs/installation/laravel",
          "$id": "laravel",
          "external": false
        },
        {
          "type": "page",
          "name": "React Router",
          "url": "/docs/installation/react-router",
          "$id": "react-router",
          "external": false
        },
        {
          "type": "page",
          "name": "Remix",
          "url": "/docs/installation/remix",
          "$id": "remix",
          "external": false
        },
        {
          "type": "page",
          "name": "Astro",
          "url": "/docs/installation/astro",
          "$id": "astro",
          "external": false
        },
        {
          "type": "page",
          "name": "TanStack Start",
          "url": "/docs/installation/tanstack",
          "$id": "tanstack",
          "external": false
        },
        {
          "type": "page",
          "name": "TanStack Router",
          "url": "/docs/installation/tanstack-router",
          "$id": "tanstack-router",
          "external": false
        },
        {
          "type": "page",
          "name": "Manual Installation",
          "url": "/docs/installation/manual",
          "$id": "manual",
          "external": false
        }
      ]
    },
    {
      "type": "folder",
      "name": "Dark mode",
      "url": "/docs/dark-mode",
      "$id": "dark-mode",
      "children": [
        {
          "type": "page",
          "name": "Dark Mode",
          "url": "/docs/dark-mode",
          "$id": "index",
          "external": false
        },
        {
          "type": "page",
          "name": "Next.js",
          "url": "/docs/dark-mode/next",
          "$id": "next",
          "external": false
        },
        {
          "type": "page",
          "name": "Vite",
          "url": "/docs/dark-mode/vite",
          "$id": "vite",
          "external": false
        },
        {
          "type": "page",
          "name": "Astro",
          "url": "/docs/dark-mode/astro",
          "$id": "astro",
          "external": false
        },
        {
          "type": "page",
          "name": "Remix",
          "url": "/docs/dark-mode/remix",
          "$id": "remix",
          "external": false
        }
      ]
    },
    {
      "type": "folder",
      "name": "Registry",
      "url": "/docs/registry",
      "$id": "registry",
      "children": [
        {
          "type": "page",
          "name": "Introduction",
          "url": "/docs/registry",
          "$id": "index",
          "external": false
        },
        {
          "type": "page",
          "name": "Getting Started",
          "url": "/docs/registry/getting-started",
          "$id": "getting-started",
          "external": false
        },
        {
          "type": "page",
          "name": "Namespaces",
          "url": "/docs/registry/namespace",
          "$id": "namespace",
          "external": false
        },
        {
          "type": "page",
          "name": "Authentication",
          "url": "/docs/registry/authentication",
          "$id": "authentication",
          "external": false
        },
        {
          "type": "page",
          "name": "Examples",
          "url": "/docs/registry/examples",
          "$id": "examples",
          "external": false
        },
        {
          "type": "page",
          "name": "MCP Server",
          "url": "/docs/registry/mcp",
          "$id": "mcp",
          "external": false
        },
        {
          "type": "page",
          "name": "Add a Registry",
          "url": "/docs/registry/registry-index",
          "$id": "registry-index",
          "external": false
        },
        {
          "type": "page",
          "name": "Open in v0",
          "url": "/docs/registry/open-in-v0",
          "$id": "open-in-v0",
          "external": false
        },
        {
          "type": "page",
          "name": "registry.json",
          "url": "/docs/registry/registry-json",
          "$id": "registry-json",
          "external": false
        },
        {
          "type": "page",
          "name": "registry-item.json",
          "url": "/docs/registry/registry-item-json",
          "$id": "registry-item-json",
          "external": false
        }
      ]
    }
  ]
}
