// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import "server-only"

import * as React from "react"

export const Index: Record<string, Record<string, any>> = {
  radix: {
    "cover-example": {
      name: "cover-example",
      title: "Cover",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/examples/cover-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/cover-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "accordion-example": {
      name: "accordion-example",
      title: "Accordion",
      description: "",
      type: "registry:example",
      registryDependencies: ["accordion"],
      files: [
        {
          path: "registry/bases/radix/examples/accordion-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/accordion-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "alert-example": {
      name: "alert-example",
      title: "Alert",
      description: "",
      type: "registry:example",
      registryDependencies: ["alert"],
      files: [
        {
          path: "registry/bases/radix/examples/alert-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/alert-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "alert-dialog-example": {
      name: "alert-dialog-example",
      title: "Alert Dialog",
      description: "",
      type: "registry:example",
      registryDependencies: ["alert-dialog", "button"],
      files: [
        {
          path: "registry/bases/radix/examples/alert-dialog-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/alert-dialog-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "aspect-ratio-example": {
      name: "aspect-ratio-example",
      title: "Aspect Ratio",
      description: "",
      type: "registry:example",
      registryDependencies: ["aspect-ratio"],
      files: [
        {
          path: "registry/bases/radix/examples/aspect-ratio-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/aspect-ratio-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "avatar-example": {
      name: "avatar-example",
      title: "Avatar",
      description: "",
      type: "registry:example",
      registryDependencies: ["avatar"],
      files: [
        {
          path: "registry/bases/radix/examples/avatar-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/avatar-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "badge-example": {
      name: "badge-example",
      title: "Badge",
      description: "",
      type: "registry:example",
      registryDependencies: ["badge"],
      files: [
        {
          path: "registry/bases/radix/examples/badge-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/badge-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "breadcrumb-example": {
      name: "breadcrumb-example",
      title: "Breadcrumb",
      description: "",
      type: "registry:example",
      registryDependencies: ["breadcrumb"],
      files: [
        {
          path: "registry/bases/radix/examples/breadcrumb-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/breadcrumb-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "button-example": {
      name: "button-example",
      title: "Button",
      description: "",
      type: "registry:example",
      registryDependencies: ["button"],
      files: [
        {
          path: "registry/bases/radix/examples/button-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/button-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "button-group-example": {
      name: "button-group-example",
      title: "Button Group",
      description: "",
      type: "registry:example",
      registryDependencies: ["button-group"],
      files: [
        {
          path: "registry/bases/radix/examples/button-group-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/button-group-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "calendar-example": {
      name: "calendar-example",
      title: "Calendar",
      description: "",
      type: "registry:example",
      registryDependencies: [
        "button",
        "calendar",
        "card",
        "drawer",
        "input",
        "label",
        "popover",
      ],
      files: [
        {
          path: "registry/bases/radix/examples/calendar-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/calendar-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "card-example": {
      name: "card-example",
      title: "Card",
      description: "",
      type: "registry:example",
      registryDependencies: ["card"],
      files: [
        {
          path: "registry/bases/radix/examples/card-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/card-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "carousel-example": {
      name: "carousel-example",
      title: "Carousel",
      description: "",
      type: "registry:example",
      registryDependencies: ["carousel"],
      files: [
        {
          path: "registry/bases/radix/examples/carousel-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/carousel-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "chart-example": {
      name: "chart-example",
      title: "Chart",
      description: "",
      type: "registry:example",
      registryDependencies: ["chart", "card"],
      files: [
        {
          path: "registry/bases/radix/examples/chart-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/chart-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "checkbox-example": {
      name: "checkbox-example",
      title: "Checkbox",
      description: "",
      type: "registry:example",
      registryDependencies: ["checkbox"],
      files: [
        {
          path: "registry/bases/radix/examples/checkbox-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/checkbox-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "collapsible-example": {
      name: "collapsible-example",
      title: "Collapsible",
      description: "",
      type: "registry:example",
      registryDependencies: ["collapsible"],
      files: [
        {
          path: "registry/bases/radix/examples/collapsible-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/collapsible-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "combobox-example": {
      name: "combobox-example",
      title: "Combobox",
      description: "",
      type: "registry:example",
      registryDependencies: ["avatar", "button", "command", "popover"],
      files: [
        {
          path: "registry/bases/radix/examples/combobox-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/combobox-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "command-example": {
      name: "command-example",
      title: "Command",
      description: "",
      type: "registry:example",
      registryDependencies: ["command"],
      files: [
        {
          path: "registry/bases/radix/examples/command-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/command-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "context-menu-example": {
      name: "context-menu-example",
      title: "Context Menu",
      description: "",
      type: "registry:example",
      registryDependencies: ["context-menu"],
      files: [
        {
          path: "registry/bases/radix/examples/context-menu-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/context-menu-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "dialog-example": {
      name: "dialog-example",
      title: "Dialog",
      description: "",
      type: "registry:example",
      registryDependencies: ["dialog"],
      files: [
        {
          path: "registry/bases/radix/examples/dialog-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/dialog-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "drawer-example": {
      name: "drawer-example",
      title: "Drawer",
      description: "",
      type: "registry:example",
      registryDependencies: ["drawer"],
      files: [
        {
          path: "registry/bases/radix/examples/drawer-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/drawer-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "dropdown-menu-example": {
      name: "dropdown-menu-example",
      title: "Dropdown Menu",
      description: "",
      type: "registry:example",
      registryDependencies: ["dropdown-menu"],
      files: [
        {
          path: "registry/bases/radix/examples/dropdown-menu-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/dropdown-menu-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "empty-example": {
      name: "empty-example",
      title: "Empty",
      description: "",
      type: "registry:example",
      registryDependencies: ["empty"],
      files: [
        {
          path: "registry/bases/radix/examples/empty-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/empty-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "field-example": {
      name: "field-example",
      title: "Field",
      description: "",
      type: "registry:example",
      registryDependencies: ["field"],
      files: [
        {
          path: "registry/bases/radix/examples/field-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/field-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "form-example": {
      name: "form-example",
      title: "Form",
      description: "",
      type: "registry:example",
      registryDependencies: [
        "button",
        "calendar",
        "checkbox",
        "form",
        "input",
        "popover",
        "radio-group",
        "select",
        "switch",
        "textarea",
      ],
      files: [
        {
          path: "registry/bases/radix/examples/form-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/form-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "hover-card-example": {
      name: "hover-card-example",
      title: "Hover Card",
      description: "",
      type: "registry:example",
      registryDependencies: ["hover-card"],
      files: [
        {
          path: "registry/bases/radix/examples/hover-card-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/hover-card-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "input-example": {
      name: "input-example",
      title: "Input",
      description: "",
      type: "registry:example",
      registryDependencies: ["input"],
      files: [
        {
          path: "registry/bases/radix/examples/input-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/input-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "input-group-example": {
      name: "input-group-example",
      title: "Input Group",
      description: "",
      type: "registry:example",
      registryDependencies: ["input-group"],
      files: [
        {
          path: "registry/bases/radix/examples/input-group-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/input-group-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "input-otp-example": {
      name: "input-otp-example",
      title: "Input OTP",
      description: "",
      type: "registry:example",
      registryDependencies: ["input-otp"],
      files: [
        {
          path: "registry/bases/radix/examples/input-otp-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/input-otp-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "item-example": {
      name: "item-example",
      title: "Item",
      description: "",
      type: "registry:example",
      registryDependencies: ["item"],
      files: [
        {
          path: "registry/bases/radix/examples/item-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/item-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "kbd-example": {
      name: "kbd-example",
      title: "Kbd",
      description: "",
      type: "registry:example",
      registryDependencies: ["kbd"],
      files: [
        {
          path: "registry/bases/radix/examples/kbd-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/kbd-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "label-example": {
      name: "label-example",
      title: "Label",
      description: "",
      type: "registry:example",
      registryDependencies: ["label"],
      files: [
        {
          path: "registry/bases/radix/examples/label-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/label-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "menubar-example": {
      name: "menubar-example",
      title: "Menubar",
      description: "",
      type: "registry:example",
      registryDependencies: ["menubar"],
      files: [
        {
          path: "registry/bases/radix/examples/menubar-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/menubar-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "native-select-example": {
      name: "native-select-example",
      title: "Native Select",
      description: "",
      type: "registry:example",
      registryDependencies: ["native-select"],
      files: [
        {
          path: "registry/bases/radix/examples/native-select-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/native-select-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "navigation-menu-example": {
      name: "navigation-menu-example",
      title: "Navigation Menu",
      description: "",
      type: "registry:example",
      registryDependencies: ["navigation-menu"],
      files: [
        {
          path: "registry/bases/radix/examples/navigation-menu-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/navigation-menu-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "pagination-example": {
      name: "pagination-example",
      title: "Pagination",
      description: "",
      type: "registry:example",
      registryDependencies: ["pagination"],
      files: [
        {
          path: "registry/bases/radix/examples/pagination-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/pagination-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "popover-example": {
      name: "popover-example",
      title: "Popover",
      description: "",
      type: "registry:example",
      registryDependencies: ["popover"],
      files: [
        {
          path: "registry/bases/radix/examples/popover-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/popover-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "progress-example": {
      name: "progress-example",
      title: "Progress",
      description: "",
      type: "registry:example",
      registryDependencies: ["progress"],
      files: [
        {
          path: "registry/bases/radix/examples/progress-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/progress-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "radio-group-example": {
      name: "radio-group-example",
      title: "Radio Group",
      description: "",
      type: "registry:example",
      registryDependencies: ["radio-group"],
      files: [
        {
          path: "registry/bases/radix/examples/radio-group-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/radio-group-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "resizable-example": {
      name: "resizable-example",
      title: "Resizable",
      description: "",
      type: "registry:example",
      registryDependencies: ["resizable"],
      files: [
        {
          path: "registry/bases/radix/examples/resizable-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/resizable-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "scroll-area-example": {
      name: "scroll-area-example",
      title: "Scroll Area",
      description: "",
      type: "registry:example",
      registryDependencies: ["scroll-area"],
      files: [
        {
          path: "registry/bases/radix/examples/scroll-area-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/scroll-area-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "select-example": {
      name: "select-example",
      title: "Select",
      description: "",
      type: "registry:example",
      registryDependencies: ["select"],
      files: [
        {
          path: "registry/bases/radix/examples/select-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/select-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "separator-example": {
      name: "separator-example",
      title: "Separator",
      description: "",
      type: "registry:example",
      registryDependencies: ["separator"],
      files: [
        {
          path: "registry/bases/radix/examples/separator-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/separator-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "sheet-example": {
      name: "sheet-example",
      title: "Sheet",
      description: "",
      type: "registry:example",
      registryDependencies: ["sheet"],
      files: [
        {
          path: "registry/bases/radix/examples/sheet-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/sheet-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "skeleton-example": {
      name: "skeleton-example",
      title: "Skeleton",
      description: "",
      type: "registry:example",
      registryDependencies: ["skeleton"],
      files: [
        {
          path: "registry/bases/radix/examples/skeleton-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/skeleton-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "slider-example": {
      name: "slider-example",
      title: "Slider",
      description: "",
      type: "registry:example",
      registryDependencies: ["slider"],
      files: [
        {
          path: "registry/bases/radix/examples/slider-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/slider-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "sonner-example": {
      name: "sonner-example",
      title: "Sonner",
      description: "",
      type: "registry:example",
      registryDependencies: ["sonner"],
      files: [
        {
          path: "registry/bases/radix/examples/sonner-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/sonner-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "spinner-example": {
      name: "spinner-example",
      title: "Spinner",
      description: "",
      type: "registry:example",
      registryDependencies: ["spinner"],
      files: [
        {
          path: "registry/bases/radix/examples/spinner-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/spinner-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "switch-example": {
      name: "switch-example",
      title: "Switch",
      description: "",
      type: "registry:example",
      registryDependencies: ["switch"],
      files: [
        {
          path: "registry/bases/radix/examples/switch-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/switch-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "table-example": {
      name: "table-example",
      title: "Table",
      description: "",
      type: "registry:example",
      registryDependencies: ["table"],
      files: [
        {
          path: "registry/bases/radix/examples/table-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/table-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "tabs-example": {
      name: "tabs-example",
      title: "Tabs",
      description: "",
      type: "registry:example",
      registryDependencies: ["tabs"],
      files: [
        {
          path: "registry/bases/radix/examples/tabs-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/tabs-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "textarea-example": {
      name: "textarea-example",
      title: "Textarea",
      description: "",
      type: "registry:example",
      registryDependencies: ["textarea"],
      files: [
        {
          path: "registry/bases/radix/examples/textarea-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/textarea-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "toggle-example": {
      name: "toggle-example",
      title: "Toggle",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle"],
      files: [
        {
          path: "registry/bases/radix/examples/toggle-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/toggle-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "toggle-group-example": {
      name: "toggle-group-example",
      title: "Toggle Group",
      description: "",
      type: "registry:example",
      registryDependencies: ["toggle-group"],
      files: [
        {
          path: "registry/bases/radix/examples/toggle-group-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/toggle-group-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "tooltip-example": {
      name: "tooltip-example",
      title: "Tooltip",
      description: "",
      type: "registry:example",
      registryDependencies: ["tooltip"],
      files: [
        {
          path: "registry/bases/radix/examples/tooltip-example.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/examples/tooltip-example.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    accordion: {
      name: "accordion",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/accordion.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/accordion.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    alert: {
      name: "alert",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/alert.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/alert.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "alert-dialog": {
      name: "alert-dialog",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [
        {
          path: "registry/bases/radix/ui/alert-dialog.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/alert-dialog.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "aspect-ratio": {
      name: "aspect-ratio",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/aspect-ratio.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/aspect-ratio.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    avatar: {
      name: "avatar",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/avatar.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/avatar.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    badge: {
      name: "badge",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/badge.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/badge.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    breadcrumb: {
      name: "breadcrumb",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/breadcrumb.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/breadcrumb.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    button: {
      name: "button",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/button.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/button.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "button-group": {
      name: "button-group",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button", "separator"],
      files: [
        {
          path: "registry/bases/radix/ui/button-group.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/button-group.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    calendar: {
      name: "calendar",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [
        {
          path: "registry/bases/radix/ui/calendar.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/calendar.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    card: {
      name: "card",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/card.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/card.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    carousel: {
      name: "carousel",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [
        {
          path: "registry/bases/radix/ui/carousel.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/carousel.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    chart: {
      name: "chart",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["card"],
      files: [
        {
          path: "registry/bases/radix/ui/chart.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/chart.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    checkbox: {
      name: "checkbox",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/checkbox.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/checkbox.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    collapsible: {
      name: "collapsible",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/collapsible.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/collapsible.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    command: {
      name: "command",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["dialog"],
      files: [
        {
          path: "registry/bases/radix/ui/command.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/command.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "context-menu": {
      name: "context-menu",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/context-menu.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/context-menu.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    dialog: {
      name: "dialog",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/dialog.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/dialog.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    drawer: {
      name: "drawer",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/drawer.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/drawer.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "dropdown-menu": {
      name: "dropdown-menu",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/dropdown-menu.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/dropdown-menu.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    empty: {
      name: "empty",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/empty.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/empty.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    field: {
      name: "field",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["label", "separator"],
      files: [
        {
          path: "registry/bases/radix/ui/field.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/field.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    form: {
      name: "form",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button", "label"],
      files: [
        {
          path: "registry/bases/radix/ui/form.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/form.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "hover-card": {
      name: "hover-card",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/hover-card.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/hover-card.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    input: {
      name: "input",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/input.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/input.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "input-group": {
      name: "input-group",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button", "input", "textarea"],
      files: [
        {
          path: "registry/bases/radix/ui/input-group.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/input-group.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "input-otp": {
      name: "input-otp",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/input-otp.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/input-otp.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    item: {
      name: "item",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["separator"],
      files: [
        {
          path: "registry/bases/radix/ui/item.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/item.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    label: {
      name: "label",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/label.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/label.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    menubar: {
      name: "menubar",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/menubar.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/menubar.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "navigation-menu": {
      name: "navigation-menu",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/navigation-menu.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import(
          "@/registry/bases/radix/ui/navigation-menu.tsx"
        )
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    pagination: {
      name: "pagination",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [
        {
          path: "registry/bases/radix/ui/pagination.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/pagination.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    popover: {
      name: "popover",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/popover.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/popover.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    progress: {
      name: "progress",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/progress.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/progress.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "radio-group": {
      name: "radio-group",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/radio-group.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/radio-group.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    resizable: {
      name: "resizable",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/resizable.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/resizable.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "scroll-area": {
      name: "scroll-area",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/scroll-area.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/scroll-area.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    select: {
      name: "select",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/select.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/select.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    separator: {
      name: "separator",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/separator.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/separator.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    sheet: {
      name: "sheet",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/sheet.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/sheet.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    sidebar: {
      name: "sidebar",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: [
        "button",
        "separator",
        "sheet",
        "tooltip",
        "input",
        "use-mobile",
        "skeleton",
      ],
      files: [
        {
          path: "registry/bases/radix/ui/sidebar.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/sidebar.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    skeleton: {
      name: "skeleton",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/skeleton.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/skeleton.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    slider: {
      name: "slider",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/slider.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/slider.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    sonner: {
      name: "sonner",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/sonner.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/sonner.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    spinner: {
      name: "spinner",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/spinner.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/spinner.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    switch: {
      name: "switch",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/switch.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/switch.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    table: {
      name: "table",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/table.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/table.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    tabs: {
      name: "tabs",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/tabs.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/tabs.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    textarea: {
      name: "textarea",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/textarea.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/textarea.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    toggle: {
      name: "toggle",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/toggle.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/toggle.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "toggle-group": {
      name: "toggle-group",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: ["toggle"],
      files: [
        {
          path: "registry/bases/radix/ui/toggle-group.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/toggle-group.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    tooltip: {
      name: "tooltip",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/tooltip.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/tooltip.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    kbd: {
      name: "kbd",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/kbd.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/kbd.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
    "native-select": {
      name: "native-select",
      title: "undefined",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/bases/radix/ui/native-select.tsx",
          type: "registry:ui",
          target: "",
        },
      ],
      component: React.lazy(async () => {
        const mod = await import("@/registry/bases/radix/ui/native-select.tsx")
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === "function" || typeof mod[key] === "object"
          ) || item.name
        return { default: mod.default || mod[exportName] }
      }),
      categories: undefined,
      meta: undefined,
    },
  },
}
