import { type Registry } from "shadcn/schema"

export const internal: Registry["items"] = [
  {
    name: "sink",
    type: "registry:internal",
    files: [
      {
        path: "internal/sink.tsx",
        type: "registry:page",
        target: "app/sink/page.tsx",
      },
    ],
    registryDependencies: [
      "accordion-example",
      "alert-dialog-example",
      "alert-example",
      "aspect-ratio-example",
      "avatar-example",
      "badge-example",
      "breadcrumb-example",
      "button-example",
      "button-group-example",
      "calendar-example",
      "card-example",
      "carousel-example",
      "chart-example",
      "checkbox-example",
      "collapsible-example",
      "combobox-example",
      "command-example",
      "context-menu-example",
      "dialog-example",
      "drawer-example",
      "dropdown-menu-example",
      "empty-example",
      "field-example",
      "hover-card-example",
      "input-example",
      "input-group-example",
      "input-otp-example",
      "item-example",
      "kbd-example",
      "label-example",
      "menubar-example",
      "native-select-example",
      "navigation-menu-example",
      "pagination-example",
      "popover-example",
      "progress-example",
      "radio-group-example",
      "resizable-example",
      "scroll-area-example",
      "select-example",
      "separator-example",
      "sheet-example",
      "skeleton-example",
      "slider-example",
      "sonner-example",
      "spinner-example",
      "switch-example",
      "table-example",
      "tabs-example",
      "textarea-example",
      "toggle-example",
      "toggle-group-example",
      "tooltip-example",
    ],
  },
]
