export const demos = [
  {
    name: "breadcrumb-demo",
    title: "Breadcrumb Demo",
    type: "registry:example",
    registryDependencies: ["breadcrumb"],
    files: [{ path: "demo/breadcrumb-demo.tsx", type: "registry:example" }],
  },
  {
    name: "breadcrumb-dropdown",
    title: "Breadcrumb Dropdown",
    type: "registry:example",
    registryDependencies: ["breadcrumb", "dropdown-menu"],
    files: [{ path: "demo/breadcrumb-dropdown.tsx", type: "registry:example" }],
  },
  {
    name: "breadcrumb-ellipsis",
    title: "Breadcrumb Ellipsis",
    type: "registry:example",
    registryDependencies: ["breadcrumb"],
    files: [{ path: "demo/breadcrumb-ellipsis.tsx", type: "registry:example" }],
  },
  {
    name: "breadcrumb-link",
    title: "Breadcrumb Link",
    type: "registry:example",
    registryDependencies: ["breadcrumb"],
    files: [{ path: "demo/breadcrumb-link.tsx", type: "registry:example" }],
  },
  {
    name: "breadcrumb-responsive",
    title: "Breadcrumb Responsive",
    type: "registry:example",
    registryDependencies: ["breadcrumb", "button", "drawer", "dropdown-menu"],
    files: [
      { path: "demo/breadcrumb-responsive.tsx", type: "registry:example" },
    ],
  },
  {
    name: "breadcrumb-separator",
    title: "Breadcrumb Separator",
    type: "registry:example",
    registryDependencies: ["breadcrumb"],
    files: [
      { path: "demo/breadcrumb-separator.tsx", type: "registry:example" },
    ],
  },
  {
    name: "pagination-demo",
    title: "Pagination Demo",
    type: "registry:example",
    registryDependencies: ["pagination"],
    files: [{ path: "demo/pagination-demo.tsx", type: "registry:example" }],
  },
  {
    name: "popover-demo",
    title: "Popover Demo",
    type: "registry:example",
    registryDependencies: ["popover"],
    files: [{ path: "demo/popover-demo.tsx", type: "registry:example" }],
  },
  {
    name: "progress-demo",
    title: "Progress Demo",
    type: "registry:example",
    registryDependencies: ["progress"],
    files: [{ path: "demo/progress-demo.tsx", type: "registry:example" }],
  },
  {
    name: "resizable-demo",
    title: "Resizable Demo",
    type: "registry:example",
    registryDependencies: ["resizable"],
    files: [{ path: "demo/resizable-demo.tsx", type: "registry:example" }],
  },
  {
    name: "resizable-demo-with-handle",
    title: "Resizable Demo With Handle",
    type: "registry:example",
    registryDependencies: ["resizable"],
    files: [
      { path: "demo/resizable-demo-with-handle.tsx", type: "registry:example" },
    ],
  },
  {
    name: "resizable-handle",
    title: "Resizable Handle",
    type: "registry:example",
    registryDependencies: ["resizable"],
    files: [{ path: "demo/resizable-handle.tsx", type: "registry:example" }],
  },
  {
    name: "resizable-vertical",
    title: "Resizable Vertical",
    type: "registry:example",
    registryDependencies: ["resizable"],
    files: [{ path: "demo/resizable-vertical.tsx", type: "registry:example" }],
  },
  {
    name: "input-group-button",
    title: "Input Group Button",
    type: "registry:example",
    registryDependencies: ["input-group", "popover"],
    files: [{ path: "demo/input-group-button.tsx", type: "registry:example" }],
  },
  {
    name: "input-group-button-group",
    title: "Input Group Button Group",
    type: "registry:example",
    registryDependencies: ["input-group", "button-group", "label"],
    files: [
      { path: "demo/input-group-button-group.tsx", type: "registry:example" },
    ],
  },
  {
    name: "input-group-custom",
    title: "Input Group Custom",
    type: "registry:example",
    registryDependencies: ["input-group"],
    files: [{ path: "demo/input-group-custom.tsx", type: "registry:example" }],
  },
  {
    name: "input-group-demo",
    title: "Input Group Demo",
    type: "registry:example",
    registryDependencies: ["input-group", "dropdown-menu", "separator", "tooltip"],
    files: [{ path: "demo/input-group-demo.tsx", type: "registry:example" }],
  },
  {
    name: "input-group-dropdown",
    title: "Input Group Dropdown",
    type: "registry:example",
    registryDependencies: ["input-group", "dropdown-menu"],
    files: [
      { path: "demo/input-group-dropdown.tsx", type: "registry:example" },
    ],
  },
  {
    name: "input-group-icon",
    title: "Input Group Icon",
    type: "registry:example",
    registryDependencies: ["input-group"],
    files: [{ path: "demo/input-group-icon.tsx", type: "registry:example" }],
  },
  {
    name: "input-group-label",
    title: "Input Group Label",
    type: "registry:example",
    registryDependencies: ["input-group", "label", "tooltip"],
    files: [{ path: "demo/input-group-label.tsx", type: "registry:example" }],
  },
  {
    name: "input-group-spinner",
    title: "Input Group Spinner",
    type: "registry:example",
    registryDependencies: ["input-group", "spinner"],
    files: [{ path: "demo/input-group-spinner.tsx", type: "registry:example" }],
  },
  {
    name: "input-group-text",
    title: "Input Group Text",
    type: "registry:example",
    registryDependencies: ["input-group"],
    files: [{ path: "demo/input-group-text.tsx", type: "registry:example" }],
  },
  {
    name: "input-group-textarea",
    title: "Input Group Textarea",
    type: "registry:example",
    registryDependencies: ["input-group"],
    files: [
      { path: "demo/input-group-textarea.tsx", type: "registry:example" },
    ],
  },
  {
    name: "input-group-tooltip",
    title: "Input Group Tooltip",
    type: "registry:example",
    registryDependencies: ["input-group", "tooltip"],
    files: [{ path: "demo/input-group-tooltip.tsx", type: "registry:example" }],
  },
  {
    name: "input-otp-controlled",
    title: "Input OTP Controlled",
    type: "registry:example",
    registryDependencies: ["input-otp"],
    files: [{ path: "demo/input-otp-controlled.tsx", type: "registry:example" }],
  },
  {
    name: "input-otp-demo",
    title: "Input OTP Demo",
    type: "registry:example",
    registryDependencies: ["input-otp"],
    files: [{ path: "demo/input-otp-demo.tsx", type: "registry:example" }],
  },
  {
    name: "input-otp-pattern",
    title: "Input OTP Pattern",
    type: "registry:example",
    registryDependencies: ["input-otp"],
    files: [{ path: "demo/input-otp-pattern.tsx", type: "registry:example" }],
  },
  {
    name: "input-otp-separator",
    title: "Input OTP Separator",
    type: "registry:example",
    registryDependencies: ["input-otp"],
    files: [{ path: "demo/input-otp-separator.tsx", type: "registry:example" }],
  },
  {
    name: "scroll-area-demo",
    title: "Scroll Area Demo",
    type: "registry:example",
    registryDependencies: ["scroll-area", "separator"],
    files: [{ path: "demo/scroll-area-demo.tsx", type: "registry:example" }],
  },
  {
    name: "scroll-area-horizontal-demo",
    title: "Scroll Area Horizontal Demo",
    type: "registry:example",
    registryDependencies: ["scroll-area"],
    files: [
      { path: "demo/scroll-area-horizontal-demo.tsx", type: "registry:example" },
    ],
  },
  {
    name: "select-demo",
    title: "Select Demo",
    type: "registry:example",
    registryDependencies: ["select"],
    files: [{ path: "demo/select-demo.tsx", type: "registry:example" }],
  },
  {
    name: "select-scrollable",
    title: "Select Scrollable",
    type: "registry:example",
    registryDependencies: ["select"],
    files: [{ path: "demo/select-scrollable.tsx", type: "registry:example" }],
  },
  {
    name: "skeleton-card",
    title: "Skeleton Card",
    type: "registry:example",
    registryDependencies: ["skeleton"],
    files: [{ path: "demo/skeleton-card.tsx", type: "registry:example" }],
  },
  {
    name: "skeleton-demo",
    title: "Skeleton Demo",
    type: "registry:example",
    registryDependencies: ["skeleton"],
    files: [{ path: "demo/skeleton-demo.tsx", type: "registry:example" }],
  },
  {
    name: "slider-demo",
    title: "Slider Demo",
    type: "registry:example",
    registryDependencies: ["slider"],
    files: [{ path: "demo/slider-demo.tsx", type: "registry:example" }],
  },
  {
    name: "sonner-demo",
    title: "Sonner Demo",
    type: "registry:example",
    registryDependencies: ["button"],
    files: [{ path: "demo/sonner-demo.tsx", type: "registry:example" }],
  },
  {
    name: "sonner-types",
    title: "Sonner Types",
    type: "registry:example",
    registryDependencies: ["button"],
    files: [{ path: "demo/sonner-types.tsx", type: "registry:example" }],
  },
  {
    name: "spinner-badge",
    title: "Spinner Badge",
    type: "registry:example",
    registryDependencies: ["badge", "spinner"],
    files: [{ path: "demo/spinner-badge.tsx", type: "registry:example" }],
  },
  {
    name: "spinner-basic",
    title: "Spinner Basic",
    type: "registry:example",
    registryDependencies: ["spinner"],
    files: [{ path: "demo/spinner-basic.tsx", type: "registry:example" }],
  },
  {
    name: "spinner-button",
    title: "Spinner Button",
    type: "registry:example",
    registryDependencies: ["button", "spinner"],
    files: [{ path: "demo/spinner-button.tsx", type: "registry:example" }],
  },
  {
    name: "spinner-color",
    title: "Spinner Color",
    type: "registry:example",
    registryDependencies: ["spinner"],
    files: [{ path: "demo/spinner-color.tsx", type: "registry:example" }],
  },
  {
    name: "spinner-custom",
    title: "Spinner Custom",
    type: "registry:example",
    registryDependencies: [],
    files: [{ path: "demo/spinner-custom.tsx", type: "registry:example" }],
  },
  {
    name: "spinner-demo",
    title: "Spinner Demo",
    type: "registry:example",
    registryDependencies: ["item", "spinner"],
    files: [{ path: "demo/spinner-demo.tsx", type: "registry:example" }],
  },
  {
    name: "spinner-empty",
    title: "Spinner Empty",
    type: "registry:example",
    registryDependencies: ["button", "empty", "spinner"],
    files: [{ path: "demo/spinner-empty.tsx", type: "registry:example" }],
  },
  {
    name: "spinner-input-group",
    title: "Spinner Input Group",
    type: "registry:example",
    registryDependencies: ["input-group", "spinner"],
    files: [{ path: "demo/spinner-input-group.tsx", type: "registry:example" }],
  },
  {
    name: "spinner-item",
    title: "Spinner Item",
    type: "registry:example",
    registryDependencies: ["button", "item", "progress", "spinner"],
    files: [{ path: "demo/spinner-item.tsx", type: "registry:example" }],
  },
  {
    name: "spinner-size",
    title: "Spinner Size",
    type: "registry:example",
    registryDependencies: ["spinner"],
    files: [{ path: "demo/spinner-size.tsx", type: "registry:example" }],
  },
  {
    name: "kbd-button",
    title: "Kbd Button",
    type: "registry:example",
    registryDependencies: ["kbd", "button"],
    files: [{ path: "demo/kbd-button.tsx", type: "registry:example" }],
  },
  {
    name: "kbd-demo",
    title: "Kbd Demo",
    type: "registry:example",
    registryDependencies: ["kbd"],
    files: [{ path: "demo/kbd-demo.tsx", type: "registry:example" }],
  },
  {
    name: "kbd-group",
    title: "Kbd Group",
    type: "registry:example",
    registryDependencies: ["kbd"],
    files: [{ path: "demo/kbd-group.tsx", type: "registry:example" }],
  },
  {
    name: "kbd-input-group",
    title: "Kbd Input Group",
    type: "registry:example",
    registryDependencies: ["kbd", "input-group"],
    files: [{ path: "demo/kbd-input-group.tsx", type: "registry:example" }],
  },
  {
    name: "kbd-tooltip",
    title: "Kbd Tooltip",
    type: "registry:example",
    registryDependencies: ["kbd", "button", "button-group", "tooltip"],
    files: [{ path: "demo/kbd-tooltip.tsx", type: "registry:example" }],
  },
  {
    name: "label-demo",
    title: "Label Demo",
    type: "registry:example",
    registryDependencies: ["label", "checkbox"],
    files: [{ path: "demo/label-demo.tsx", type: "registry:example" }],
  },
  {
    name: "menubar-demo",
    title: "Menubar Demo",
    type: "registry:example",
    registryDependencies: ["menubar"],
    files: [{ path: "demo/menubar-demo.tsx", type: "registry:example" }],
  },
  {
    name: "native-select-demo",
    title: "Native Select Demo",
    type: "registry:example",
    registryDependencies: ["native-select"],
    files: [{ path: "demo/native-select-demo.tsx", type: "registry:example" }],
  },
  {
    name: "native-select-disabled",
    title: "Native Select Disabled",
    type: "registry:example",
    registryDependencies: ["native-select"],
    files: [
      { path: "demo/native-select-disabled.tsx", type: "registry:example" },
    ],
  },
  {
    name: "native-select-groups",
    title: "Native Select Groups",
    type: "registry:example",
    registryDependencies: ["native-select"],
    files: [
      { path: "demo/native-select-groups.tsx", type: "registry:example" },
    ],
  },
  {
    name: "native-select-invalid",
    title: "Native Select Invalid",
    type: "registry:example",
    registryDependencies: ["native-select"],
    files: [
      { path: "demo/native-select-invalid.tsx", type: "registry:example" },
    ],
  },
  {
    name: "navigation-menu-demo",
    title: "Navigation Menu Demo",
    type: "registry:example",
    registryDependencies: ["navigation-menu"],
    files: [
      { path: "demo/navigation-menu-demo.tsx", type: "registry:example" },
    ],
  },
  {
    name: "switch-demo",
    title: "Switch Demo",
    type: "registry:example",
    registryDependencies: ["switch"],
    files: [{ path: "demo/switch-demo.tsx", type: "registry:example" }],
  },
  {
    name: "table-demo",
    title: "Table Demo",
    type: "registry:example",
    registryDependencies: ["table"],
    files: [{ path: "demo/table-demo.tsx", type: "registry:example" }],
  },
  {
    name: "tabs-demo",
    title: "Tabs Demo",
    type: "registry:example",
    registryDependencies: ["tabs"],
    files: [{ path: "demo/tabs-demo.tsx", type: "registry:example" }],
  },
  {
    name: "tooltip-demo",
    title: "Tooltip Demo",
    type: "registry:example",
    registryDependencies: ["tooltip", "button"],
    files: [{ path: "demo/tooltip-demo.tsx", type: "registry:example" }],
  },
  {
    name: "typography-blockquote",
    title: "Typography Blockquote",
    type: "registry:example",
    registryDependencies: [],
    files: [{ path: "demo/typography-blockquote.tsx", type: "registry:example" }],
  },
  {
    name: "typography-demo",
    title: "Typography Demo",
    type: "registry:example",
    registryDependencies: [],
    files: [{ path: "demo/typography-demo.tsx", type: "registry:example" }],
  },
  {
    name: "typography-h1",
    title: "Typography H1",
    type: "registry:example",
    registryDependencies: [],
    files: [{ path: "demo/typography-h1.tsx", type: "registry:example" }],
  },
  {
    name: "typography-h2",
    title: "Typography H2",
    type: "registry:example",
    registryDependencies: [],
    files: [{ path: "demo/typography-h2.tsx", type: "registry:example" }],
  },
  {
    name: "typography-h3",
    title: "Typography H3",
    type: "registry:example",
    registryDependencies: [],
    files: [{ path: "demo/typography-h3.tsx", type: "registry:example" }],
  },
  {
    name: "typography-h4",
    title: "Typography H4",
    type: "registry:example",
    registryDependencies: [],
    files: [{ path: "demo/typography-h4.tsx", type: "registry:example" }],
  },
  {
    name: "typography-inline-code",
    title: "Typography Inline Code",
    type: "registry:example",
    registryDependencies: [],
    files: [
      { path: "demo/typography-inline-code.tsx", type: "registry:example" },
    ],
  },
  {
    name: "typography-large",
    title: "Typography Large",
    type: "registry:example",
    registryDependencies: [],
    files: [{ path: "demo/typography-large.tsx", type: "registry:example" }],
  },
  {
    name: "typography-lead",
    title: "Typography Lead",
    type: "registry:example",
    registryDependencies: [],
    files: [{ path: "demo/typography-lead.tsx", type: "registry:example" }],
  },
  {
    name: "typography-list",
    title: "Typography List",
    type: "registry:example",
    registryDependencies: [],
    files: [{ path: "demo/typography-list.tsx", type: "registry:example" }],
  },
  {
    name: "typography-muted",
    title: "Typography Muted",
    type: "registry:example",
    registryDependencies: [],
    files: [{ path: "demo/typography-muted.tsx", type: "registry:example" }],
  },
  {
    name: "typography-p",
    title: "Typography P",
    type: "registry:example",
    registryDependencies: [],
    files: [{ path: "demo/typography-p.tsx", type: "registry:example" }],
  },
  {
    name: "typography-small",
    title: "Typography Small",
    type: "registry:example",
    registryDependencies: [],
    files: [{ path: "demo/typography-small.tsx", type: "registry:example" }],
  },
  {
    name: "typography-table",
    title: "Typography Table",
    type: "registry:example",
    registryDependencies: [],
    files: [{ path: "demo/typography-table.tsx", type: "registry:example" }],
  },
  {
    name: "toggle-demo",
    title: "Toggle Demo",
    type: "registry:example",
    registryDependencies: ["toggle"],
    files: [{ path: "demo/toggle-demo.tsx", type: "registry:example" }],
  },
  {
    name: "toggle-disabled",
    title: "Toggle Disabled",
    type: "registry:example",
    registryDependencies: ["toggle"],
    files: [{ path: "demo/toggle-disabled.tsx", type: "registry:example" }],
  },
  {
    name: "toggle-lg",
    title: "Toggle Large",
    type: "registry:example",
    registryDependencies: ["toggle"],
    files: [{ path: "demo/toggle-lg.tsx", type: "registry:example" }],
  },
  {
    name: "toggle-outline",
    title: "Toggle Outline",
    type: "registry:example",
    registryDependencies: ["toggle"],
    files: [{ path: "demo/toggle-outline.tsx", type: "registry:example" }],
  },
  {
    name: "toggle-sm",
    title: "Toggle Small",
    type: "registry:example",
    registryDependencies: ["toggle"],
    files: [{ path: "demo/toggle-sm.tsx", type: "registry:example" }],
  },
  {
    name: "toggle-with-text",
    title: "Toggle With Text",
    type: "registry:example",
    registryDependencies: ["toggle"],
    files: [{ path: "demo/toggle-with-text.tsx", type: "registry:example" }],
  },
  {
    name: "toggle-group-demo",
    title: "Toggle Group Demo",
    type: "registry:example",
    registryDependencies: ["toggle-group"],
    files: [{ path: "demo/toggle-group-demo.tsx", type: "registry:example" }],
  },
  {
    name: "toggle-group-disabled",
    title: "Toggle Group Disabled",
    type: "registry:example",
    registryDependencies: ["toggle-group"],
    files: [
      { path: "demo/toggle-group-disabled.tsx", type: "registry:example" },
    ],
  },
  {
    name: "toggle-group-lg",
    title: "Toggle Group Large",
    type: "registry:example",
    registryDependencies: ["toggle-group"],
    files: [{ path: "demo/toggle-group-lg.tsx", type: "registry:example" }],
  },
  {
    name: "toggle-group-outline",
    title: "Toggle Group Outline",
    type: "registry:example",
    registryDependencies: ["toggle-group"],
    files: [{ path: "demo/toggle-group-outline.tsx", type: "registry:example" }],
  },
  {
    name: "toggle-group-single",
    title: "Toggle Group Single",
    type: "registry:example",
    registryDependencies: ["toggle-group"],
    files: [{ path: "demo/toggle-group-single.tsx", type: "registry:example" }],
  },
  {
    name: "toggle-group-sm",
    title: "Toggle Group Small",
    type: "registry:example",
    registryDependencies: ["toggle-group"],
    files: [{ path: "demo/toggle-group-sm.tsx", type: "registry:example" }],
  },
  {
    name: "toggle-group-spacing",
    title: "Toggle Group Spacing",
    type: "registry:example",
    registryDependencies: ["toggle-group"],
    files: [{ path: "demo/toggle-group-spacing.tsx", type: "registry:example" }],
  },
  {
    name: "command-demo",
    title: "Command Demo",
    type: "registry:example",
    registryDependencies: ["command"],
    files: [{ path: "demo/command-demo.tsx", type: "registry:example" }],
  },
  {
    name: "command-dialog",
    title: "Command Dialog",
    type: "registry:example",
    registryDependencies: ["command"],
    files: [{ path: "demo/command-dialog.tsx", type: "registry:example" }],
  },
  {
    name: "item-avatar",
    title: "Item Avatar",
    type: "registry:example",
    registryDependencies: ["item", "avatar", "button"],
    files: [{ path: "demo/item-avatar.tsx", type: "registry:example" }],
  },
  {
    name: "item-demo",
    title: "Item Demo",
    type: "registry:example",
    registryDependencies: ["item", "button"],
    files: [{ path: "demo/item-demo.tsx", type: "registry:example" }],
  },
  {
    name: "item-dropdown",
    title: "Item Dropdown",
    type: "registry:example",
    registryDependencies: ["item", "avatar", "button", "dropdown-menu"],
    files: [{ path: "demo/item-dropdown.tsx", type: "registry:example" }],
  },
  {
    name: "item-group",
    title: "Item Group",
    type: "registry:example",
    registryDependencies: ["item", "avatar", "button"],
    files: [{ path: "demo/item-group.tsx", type: "registry:example" }],
  },
  {
    name: "item-header",
    title: "Item Header",
    type: "registry:example",
    registryDependencies: ["item"],
    files: [{ path: "demo/item-header.tsx", type: "registry:example" }],
  },
  {
    name: "item-icon",
    title: "Item Icon",
    type: "registry:example",
    registryDependencies: ["item", "button"],
    files: [{ path: "demo/item-icon.tsx", type: "registry:example" }],
  },
  {
    name: "item-image",
    title: "Item Image",
    type: "registry:example",
    registryDependencies: ["item"],
    files: [{ path: "demo/item-image.tsx", type: "registry:example" }],
  },
  {
    name: "item-link",
    title: "Item Link",
    type: "registry:example",
    registryDependencies: ["item"],
    files: [{ path: "demo/item-link.tsx", type: "registry:example" }],
  },
  {
    name: "item-size",
    title: "Item Size",
    type: "registry:example",
    registryDependencies: ["item", "button"],
    files: [{ path: "demo/item-size.tsx", type: "registry:example" }],
  },
  {
    name: "item-variant",
    title: "Item Variant",
    type: "registry:example",
    registryDependencies: ["item", "button"],
    files: [{ path: "demo/item-variant.tsx", type: "registry:example" }],
  },
]
