import path from "path"
import fs from "fs-extra"
import { describe, expect, it } from "vitest"

import { createFixtureTestDirectory, npxShadcn } from "../utils/helpers"

// Files `shadcn add` edits besides the item's own files: the Next.js layout
// for a font item, and tailwind.config on Tailwind v3.
describe("shadcn add edits project config", () => {
  it("wires a font into the Next.js layout", async () => {
    const fixturePath = await createFixtureTestDirectory("next-app-init")
    // The create-next-app 15 layout that new projects start from.
    await fs.writeFile(
      path.join(fixturePath, "app/layout.tsx"),
      `import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={\`\${geistSans.variable} \${geistMono.variable} antialiased\`}
      >
        {children}
      </body>
    </html>
  );
}
`
    )

    const result = await npxShadcn(fixturePath, [
      "add",
      "../../fixtures/registry/font-inter.json",
    ])
    expect(result.exitCode, result.stderr).toBe(0)

    expect(await fs.readFile(path.join(fixturePath, "app/layout.tsx"), "utf8"))
      .toMatchInlineSnapshot(`
      "import type { Metadata } from "next";
      import { Geist, Geist_Mono, Inter } from "next/font/google";
      import "./globals.css";
      import { cn } from "@/lib/utils";

      const inter = Inter({subsets:['latin'],variable:'--font-sans'});

      const geistSans = Geist({
        variable: "--font-geist-sans",
        subsets: ["latin"],
      });

      const geistMono = Geist_Mono({
        variable: "--font-geist-mono",
        subsets: ["latin"],
      });

      export const metadata: Metadata = {
        title: "Create Next App",
        description: "Generated by create next app",
      };

      export default function RootLayout({
        children,
      }: Readonly<{
        children: React.ReactNode;
      }>) {
        return (
          <html lang="en" className={cn("font-sans", inter.variable)}>
            <body
              className={\`\${geistSans.variable} \${geistMono.variable} antialiased\`}
            >
              {children}
            </body>
          </html>
        );
      }
      "
    `)
  })

  it("merges tailwind.config on Tailwind v3", async () => {
    const fixturePath = await createFixtureTestDirectory("next-app-tailwind-v3")

    for (const item of ["tailwind-v3-accordion", "tailwind-v3-sidebar"]) {
      const result = await npxShadcn(fixturePath, [
        "add",
        `../../fixtures/registry/${item}.json`,
      ])
      expect(result.exitCode, result.stderr).toBe(0)
    }

    expect(
      await fs.readFile(path.join(fixturePath, "tailwind.config.ts"), "utf8")
    ).toMatchInlineSnapshot(`
      "import type { Config } from "tailwindcss"

      const config = {
        darkMode: ["class"],
        content: [
          './pages/**/*.{ts,tsx}',
          './components/**/*.{ts,tsx}',
          './app/**/*.{ts,tsx}',
          './src/**/*.{ts,tsx}',
      	],
        prefix: "",
        theme: {
        	container: {
        		center: true,
        		padding: '2rem',
        		screens: {
        			'2xl': '1400px'
        		}
        	},
        	extend: {
        		colors: {
        			border: 'hsl(var(--border))',
        			input: 'hsl(var(--input))',
        			ring: 'hsl(var(--ring))',
        			background: 'hsl(var(--background))',
        			foreground: 'hsl(var(--foreground))',
        			primary: {
        				DEFAULT: 'hsl(var(--primary))',
        				foreground: 'hsl(var(--primary-foreground))'
        			},
        			secondary: {
        				DEFAULT: 'hsl(var(--secondary))',
        				foreground: 'hsl(var(--secondary-foreground))'
        			},
        			destructive: {
        				DEFAULT: 'hsl(var(--destructive))',
        				foreground: 'hsl(var(--destructive-foreground))'
        			},
        			muted: {
        				DEFAULT: 'hsl(var(--muted))',
        				foreground: 'hsl(var(--muted-foreground))'
        			},
        			accent: {
        				DEFAULT: 'hsl(var(--accent))',
        				foreground: 'hsl(var(--accent-foreground))'
        			},
        			popover: {
        				DEFAULT: 'hsl(var(--popover))',
        				foreground: 'hsl(var(--popover-foreground))'
        			},
        			card: {
        				DEFAULT: 'hsl(var(--card))',
        				foreground: 'hsl(var(--card-foreground))'
        			},
        			sidebar: {
        				DEFAULT: 'hsl(var(--sidebar-background))',
        				foreground: 'hsl(var(--sidebar-foreground))',
        				primary: 'hsl(var(--sidebar-primary))',
        				'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
        				accent: 'hsl(var(--sidebar-accent))',
        				'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
        				border: 'hsl(var(--sidebar-border))',
        				ring: 'hsl(var(--sidebar-ring))'
        			}
        		},
        		borderRadius: {
        			lg: 'var(--radius)',
        			md: 'calc(var(--radius) - 2px)',
        			sm: 'calc(var(--radius) - 4px)'
        		},
        		keyframes: {
        			'accordion-down': {
        				from: {
        					height: '0'
        				},
        				to: {
        					height: 'var(--radix-accordion-content-height)'
        				}
        			},
        			'accordion-up': {
        				from: {
        					height: 'var(--radix-accordion-content-height)'
        				},
        				to: {
        					height: '0'
        				}
        			}
        		},
        		animation: {
        			'accordion-down': 'accordion-down 0.2s ease-out',
        			'accordion-up': 'accordion-up 0.2s ease-out'
        		}
        	}
        },
        plugins: [require("tailwindcss-animate")],
      } satisfies Config

      export default config
      "
    `)
  })
})
