/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "accordion": {
    name: "accordion",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/accordion.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/accordion.tsx")),
    meta: undefined,
  },
  "alert": {
    name: "alert",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/alert.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/alert.tsx")),
    meta: undefined,
  },
  "alert-dialog": {
    name: "alert-dialog",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button"],
    files: [{
      path: "registry/ui/alert-dialog.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/alert-dialog.tsx")),
    meta: undefined,
  },
  "aspect-ratio": {
    name: "aspect-ratio",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/aspect-ratio.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/aspect-ratio.tsx")),
    meta: undefined,
  },
  "avatar": {
    name: "avatar",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/avatar.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/avatar.tsx")),
    meta: undefined,
  },
  "badge": {
    name: "badge",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/badge.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/badge.tsx")),
    meta: undefined,
  },
  "breadcrumb": {
    name: "breadcrumb",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/breadcrumb.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/breadcrumb.tsx")),
    meta: undefined,
  },
  "button": {
    name: "button",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/button.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/button.tsx")),
    meta: undefined,
  },
  "calendar": {
    name: "calendar",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button"],
    files: [{
      path: "registry/ui/calendar.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/calendar.tsx")),
    meta: undefined,
  },
  "card": {
    name: "card",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/card.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/card.tsx")),
    meta: undefined,
  },
  "carousel": {
    name: "carousel",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button"],
    files: [{
      path: "registry/ui/carousel.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/carousel.tsx")),
    meta: undefined,
  },
  "chart": {
    name: "chart",
    description: "",
    type: "registry:ui",
    registryDependencies: ["card"],
    files: [{
      path: "registry/ui/chart.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/chart.tsx")),
    meta: undefined,
  },
  "checkbox": {
    name: "checkbox",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/checkbox.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/checkbox.tsx")),
    meta: undefined,
  },
  "collapsible": {
    name: "collapsible",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/collapsible.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/collapsible.tsx")),
    meta: undefined,
  },
  "command": {
    name: "command",
    description: "",
    type: "registry:ui",
    registryDependencies: ["dialog"],
    files: [{
      path: "registry/ui/command.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/command.tsx")),
    meta: undefined,
  },
  "context-menu": {
    name: "context-menu",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/context-menu.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/context-menu.tsx")),
    meta: undefined,
  },
  "dialog": {
    name: "dialog",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/dialog.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/dialog.tsx")),
    meta: undefined,
  },
  "drawer": {
    name: "drawer",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/drawer.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/drawer.tsx")),
    meta: undefined,
  },
  "dropdown-menu": {
    name: "dropdown-menu",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/dropdown-menu.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/dropdown-menu.tsx")),
    meta: undefined,
  },
  "form": {
    name: "form",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button","label"],
    files: [{
      path: "registry/ui/form.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/form.tsx")),
    meta: undefined,
  },
  "hover-card": {
    name: "hover-card",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/hover-card.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/hover-card.tsx")),
    meta: undefined,
  },
  "input": {
    name: "input",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/input.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/input.tsx")),
    meta: undefined,
  },
  "input-otp": {
    name: "input-otp",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/input-otp.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/input-otp.tsx")),
    meta: undefined,
  },
  "label": {
    name: "label",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/label.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/label.tsx")),
    meta: undefined,
  },
  "menubar": {
    name: "menubar",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/menubar.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/menubar.tsx")),
    meta: undefined,
  },
  "navigation-menu": {
    name: "navigation-menu",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/navigation-menu.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/navigation-menu.tsx")),
    meta: undefined,
  },
  "pagination": {
    name: "pagination",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button"],
    files: [{
      path: "registry/ui/pagination.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/pagination.tsx")),
    meta: undefined,
  },
  "popover": {
    name: "popover",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/popover.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/popover.tsx")),
    meta: undefined,
  },
  "progress": {
    name: "progress",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/progress.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/progress.tsx")),
    meta: undefined,
  },
  "radio-group": {
    name: "radio-group",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/radio-group.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/radio-group.tsx")),
    meta: undefined,
  },
  "resizable": {
    name: "resizable",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/resizable.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/resizable.tsx")),
    meta: undefined,
  },
  "scroll-area": {
    name: "scroll-area",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/scroll-area.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/scroll-area.tsx")),
    meta: undefined,
  },
  "select": {
    name: "select",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/select.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/select.tsx")),
    meta: undefined,
  },
  "separator": {
    name: "separator",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/separator.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/separator.tsx")),
    meta: undefined,
  },
  "sheet": {
    name: "sheet",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/sheet.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/sheet.tsx")),
    meta: undefined,
  },
  "sidebar": {
    name: "sidebar",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button","separator","sheet","tooltip","input","use-mobile","skeleton"],
    files: [{
      path: "registry/ui/sidebar.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/sidebar.tsx")),
    meta: undefined,
  },
  "skeleton": {
    name: "skeleton",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/skeleton.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/skeleton.tsx")),
    meta: undefined,
  },
  "slider": {
    name: "slider",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/slider.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/slider.tsx")),
    meta: undefined,
  },
  "sonner": {
    name: "sonner",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/sonner.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/sonner.tsx")),
    meta: undefined,
  },
  "switch": {
    name: "switch",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/switch.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/switch.tsx")),
    meta: undefined,
  },
  "table": {
    name: "table",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/table.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/table.tsx")),
    meta: undefined,
  },
  "tabs": {
    name: "tabs",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/tabs.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/tabs.tsx")),
    meta: undefined,
  },
  "textarea": {
    name: "textarea",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/textarea.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/textarea.tsx")),
    meta: undefined,
  },
  "toggle": {
    name: "toggle",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/toggle.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/toggle.tsx")),
    meta: undefined,
  },
  "toggle-group": {
    name: "toggle-group",
    description: "",
    type: "registry:ui",
    registryDependencies: ["toggle"],
    files: [{
      path: "registry/ui/toggle-group.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/toggle-group.tsx")),
    meta: undefined,
  },
  "tooltip": {
    name: "tooltip",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/ui/tooltip.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/ui/tooltip.tsx")),
    meta: undefined,
  },
  "sidebar-01": {
    name: "sidebar-01",
    description: "A simple sidebar with navigation grouped by section.",
    type: "registry:block",
    registryDependencies: ["sidebar","breadcrumb","separator","label","dropdown-menu"],
    files: [{
      path: "registry/blocks/sidebar-01/page.tsx",
      type: "registry:page",
      target: "app/dashboard/page.tsx"
    },{
      path: "registry/blocks/sidebar-01/components/app-sidebar.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-01/components/search-form.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-01/components/version-switcher.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/blocks/sidebar-01/page.tsx")),
    meta: undefined,
  },
  "sidebar-02": {
    name: "sidebar-02",
    description: "A sidebar with collapsible sections.",
    type: "registry:block",
    registryDependencies: ["sidebar","breadcrumb","separator","label","dropdown-menu"],
    files: [{
      path: "registry/blocks/sidebar-02/page.tsx",
      type: "registry:page",
      target: "app/dashboard/page.tsx"
    },{
      path: "registry/blocks/sidebar-02/components/app-sidebar.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-02/components/search-form.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-02/components/version-switcher.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/blocks/sidebar-02/page.tsx")),
    meta: undefined,
  },
  "sidebar-03": {
    name: "sidebar-03",
    description: "A sidebar with submenus.",
    type: "registry:block",
    registryDependencies: ["sidebar","breadcrumb"],
    files: [{
      path: "registry/blocks/sidebar-03/page.tsx",
      type: "registry:page",
      target: "app/dashboard/page.tsx"
    },{
      path: "registry/blocks/sidebar-03/components/app-sidebar.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/blocks/sidebar-03/page.tsx")),
    meta: undefined,
  },
  "sidebar-04": {
    name: "sidebar-04",
    description: "A floating sidebar with submenus.",
    type: "registry:block",
    registryDependencies: ["sidebar","breadcrumb","separator"],
    files: [{
      path: "registry/blocks/sidebar-04/page.tsx",
      type: "registry:page",
      target: "app/dashboard/page.tsx"
    },{
      path: "registry/blocks/sidebar-04/components/app-sidebar.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/blocks/sidebar-04/page.tsx")),
    meta: undefined,
  },
  "sidebar-05": {
    name: "sidebar-05",
    description: "A sidebar with collapsible submenus.",
    type: "registry:block",
    registryDependencies: ["sidebar","breadcrumb","separator","label","collapsible"],
    files: [{
      path: "registry/blocks/sidebar-05/page.tsx",
      type: "registry:page",
      target: "app/dashboard/page.tsx"
    },{
      path: "registry/blocks/sidebar-05/components/app-sidebar.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-05/components/search-form.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/blocks/sidebar-05/page.tsx")),
    meta: undefined,
  },
  "sidebar-06": {
    name: "sidebar-06",
    description: "A sidebar with submenus as dropdowns.",
    type: "registry:block",
    registryDependencies: ["sidebar","breadcrumb","separator","card","dropdown-menu"],
    files: [{
      path: "registry/blocks/sidebar-06/page.tsx",
      type: "registry:page",
      target: "app/dashboard/page.tsx"
    },{
      path: "registry/blocks/sidebar-06/components/app-sidebar.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-06/components/nav-main.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-06/components/sidebar-opt-in-form.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/blocks/sidebar-06/page.tsx")),
    meta: undefined,
  },
  "sidebar-07": {
    name: "sidebar-07",
    description: "A sidebar that collapses to icons.",
    type: "registry:block",
    registryDependencies: ["sidebar","breadcrumb","separator","collapsible","dropdown-menu","avatar"],
    files: [{
      path: "registry/blocks/sidebar-07/page.tsx",
      type: "registry:page",
      target: "app/dashboard/page.tsx"
    },{
      path: "registry/blocks/sidebar-07/components/app-sidebar.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-07/components/nav-main.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-07/components/nav-projects.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-07/components/nav-user.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-07/components/team-switcher.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/blocks/sidebar-07/page.tsx")),
    meta: undefined,
  },
  "sidebar-08": {
    name: "sidebar-08",
    description: "An inset sidebar with secondary navigation.",
    type: "registry:block",
    registryDependencies: ["sidebar","breadcrumb","separator","collapsible","dropdown-menu","avatar"],
    files: [{
      path: "registry/blocks/sidebar-08/page.tsx",
      type: "registry:page",
      target: "app/dashboard/page.tsx"
    },{
      path: "registry/blocks/sidebar-08/components/app-sidebar.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-08/components/nav-main.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-08/components/nav-projects.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-08/components/nav-secondary.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-08/components/nav-user.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/blocks/sidebar-08/page.tsx")),
    meta: undefined,
  },
  "sidebar-09": {
    name: "sidebar-09",
    description: "Collapsible nested sidebars.",
    type: "registry:block",
    registryDependencies: ["sidebar","breadcrumb","separator","collapsible","dropdown-menu","avatar","switch"],
    files: [{
      path: "registry/blocks/sidebar-09/page.tsx",
      type: "registry:page",
      target: "app/dashboard/page.tsx"
    },{
      path: "registry/blocks/sidebar-09/components/app-sidebar.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-09/components/nav-user.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/blocks/sidebar-09/page.tsx")),
    meta: undefined,
  },
  "sidebar-10": {
    name: "sidebar-10",
    description: "A sidebar in a popover.",
    type: "registry:block",
    registryDependencies: ["sidebar","breadcrumb","separator","popover","collapsible","dropdown-menu"],
    files: [{
      path: "registry/blocks/sidebar-10/page.tsx",
      type: "registry:page",
      target: "app/dashboard/page.tsx"
    },{
      path: "registry/blocks/sidebar-10/components/app-sidebar.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-10/components/nav-actions.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-10/components/nav-favorites.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-10/components/nav-main.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-10/components/nav-secondary.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-10/components/nav-workspaces.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-10/components/team-switcher.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/blocks/sidebar-10/page.tsx")),
    meta: undefined,
  },
  "sidebar-11": {
    name: "sidebar-11",
    description: "A sidebar with a collapsible file tree.",
    type: "registry:block",
    registryDependencies: ["sidebar","breadcrumb","separator","collapsible"],
    files: [{
      path: "registry/blocks/sidebar-11/page.tsx",
      type: "registry:page",
      target: "app/dashboard/page.tsx"
    },{
      path: "registry/blocks/sidebar-11/components/app-sidebar.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/blocks/sidebar-11/page.tsx")),
    meta: undefined,
  },
  "sidebar-12": {
    name: "sidebar-12",
    description: "A sidebar with a calendar.",
    type: "registry:block",
    registryDependencies: ["sidebar","breadcrumb","separator","collapsible","calendar","dropdown-menu","avatar"],
    files: [{
      path: "registry/blocks/sidebar-12/page.tsx",
      type: "registry:page",
      target: "app/dashboard/page.tsx"
    },{
      path: "registry/blocks/sidebar-12/components/app-sidebar.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-12/components/calendars.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-12/components/date-picker.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-12/components/nav-user.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/blocks/sidebar-12/page.tsx")),
    meta: undefined,
  },
  "sidebar-13": {
    name: "sidebar-13",
    description: "A sidebar in a dialog.",
    type: "registry:block",
    registryDependencies: ["sidebar","breadcrumb","button","dialog"],
    files: [{
      path: "registry/blocks/sidebar-13/page.tsx",
      type: "registry:page",
      target: "app/dashboard/page.tsx"
    },{
      path: "registry/blocks/sidebar-13/components/settings-dialog.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/blocks/sidebar-13/page.tsx")),
    meta: undefined,
  },
  "sidebar-14": {
    name: "sidebar-14",
    description: "A sidebar on the right.",
    type: "registry:block",
    registryDependencies: ["sidebar","breadcrumb"],
    files: [{
      path: "registry/blocks/sidebar-14/page.tsx",
      type: "registry:page",
      target: "app/dashboard/page.tsx"
    },{
      path: "registry/blocks/sidebar-14/components/app-sidebar.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/blocks/sidebar-14/page.tsx")),
    meta: undefined,
  },
  "sidebar-15": {
    name: "sidebar-15",
    description: "A left and right sidebar.",
    type: "registry:block",
    registryDependencies: ["sidebar","breadcrumb","separator","popover","collapsible","dropdown-menu","calendar","avatar"],
    files: [{
      path: "registry/blocks/sidebar-15/page.tsx",
      type: "registry:page",
      target: "app/dashboard/page.tsx"
    },{
      path: "registry/blocks/sidebar-15/components/calendars.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-15/components/date-picker.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-15/components/nav-favorites.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-15/components/nav-main.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-15/components/nav-secondary.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-15/components/nav-user.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-15/components/nav-workspaces.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-15/components/sidebar-left.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-15/components/sidebar-right.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-15/components/team-switcher.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/blocks/sidebar-15/page.tsx")),
    meta: undefined,
  },
  "sidebar-16": {
    name: "sidebar-16",
    description: "A sidebar with a sticky site header.",
    type: "registry:block",
    registryDependencies: ["sidebar","breadcrumb","separator","collapsible","dropdown-menu","avatar","button"],
    files: [{
      path: "registry/blocks/sidebar-16/page.tsx",
      type: "registry:page",
      target: "app/dashboard/page.tsx"
    },{
      path: "registry/blocks/sidebar-16/components/app-sidebar.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-16/components/nav-main.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-16/components/nav-projects.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-16/components/nav-secondary.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-16/components/nav-user.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-16/components/search-form.tsx",
      type: "registry:component",
      target: ""
    },{
      path: "registry/blocks/sidebar-16/components/site-header.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/blocks/sidebar-16/page.tsx")),
    meta: undefined,
  },
  "login-01": {
    name: "login-01",
    description: "A simple login form.",
    type: "registry:block",
    registryDependencies: ["button","card","input","label"],
    files: [{
      path: "registry/blocks/login-01/page.tsx",
      type: "registry:page",
      target: "app/login/page.tsx"
    },{
      path: "registry/blocks/login-01/components/login-form.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/blocks/login-01/page.tsx")),
    meta: undefined,
  },
  "login-02": {
    name: "login-02",
    description: "A two column login page with a cover image.",
    type: "registry:block",
    registryDependencies: ["button","card","input","label"],
    files: [{
      path: "registry/blocks/login-02/page.tsx",
      type: "registry:page",
      target: "app/login/page.tsx"
    },{
      path: "registry/blocks/login-02/components/login-form.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/blocks/login-02/page.tsx")),
    meta: undefined,
  },
  "login-03": {
    name: "login-03",
    description: "A login page with a muted background color.",
    type: "registry:block",
    registryDependencies: ["button","card","input","label"],
    files: [{
      path: "registry/blocks/login-03/page.tsx",
      type: "registry:page",
      target: "app/login/page.tsx"
    },{
      path: "registry/blocks/login-03/components/login-form.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/blocks/login-03/page.tsx")),
    meta: undefined,
  },
  "login-04": {
    name: "login-04",
    description: "A login page with form and image.",
    type: "registry:block",
    registryDependencies: ["button","card","input","label"],
    files: [{
      path: "registry/blocks/login-04/page.tsx",
      type: "registry:page",
      target: "app/login/page.tsx"
    },{
      path: "registry/blocks/login-04/components/login-form.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/blocks/login-04/page.tsx")),
    meta: undefined,
  },
  "login-05": {
    name: "login-05",
    description: "A simple email-only login page.",
    type: "registry:block",
    registryDependencies: ["button","card","input","label"],
    files: [{
      path: "registry/blocks/login-05/page.tsx",
      type: "registry:page",
      target: "app/login/page.tsx"
    },{
      path: "registry/blocks/login-05/components/login-form.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/blocks/login-05/page.tsx")),
    meta: undefined,
  },
  "use-mobile": {
    name: "use-mobile",
    description: "",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "registry/hooks/use-mobile.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/hooks/use-mobile.ts")),
    meta: undefined,
  },
  },