export const components = [
  {
    component: "accordion",
    name: "Accordion",
    dependencies: ["@radix-ui/react-accordion"],
    files: ["components/ui/accordion.tsx"],
  },
  {
    component: "alert",
    name: "Alert",
    files: ["components/ui/alert.tsx"],
  },
  {
    component: "alert-dialog",
    name: "Alert Dialog",
    dependencies: ["@radix-ui/react-alert-dialog"],
    files: ["components/ui/alert-dialog.tsx"],
  },
  {
    component: "aspect-ratio",
    name: "Aspect Ratio",
    dependencies: ["@radix-ui/react-aspect-ratio"],
    files: ["components/ui/aspect-ratio.tsx"],
  },
  {
    component: "avatar",
    name: "Avatar",
    dependencies: ["@radix-ui/react-avatar"],
    files: ["components/ui/avatar.tsx"],
  },
  {
    component: "badge",
    name: "Badge",
    files: ["components/ui/badge.tsx"],
  },
  {
    component: "button",
    name: "Button",
    dependencies: ["@radix-ui/react-slot"],
    files: ["components/ui/button.tsx"],
  },
  {
    component: "card",
    name: "Card",
    files: ["components/ui/card.tsx"],
  },
  {
    component: "calendar",
    name: "Calendar",
    dependencies: ["react-day-picker", "date-fns"],
    files: ["components/ui/calendar.tsx"],
  },
  {
    component: "checkbox",
    name: "Checkbox",
    dependencies: ["@radix-ui/react-checkbox"],
    files: ["components/ui/checkbox.tsx"],
  },
  {
    component: "collapsible",
    name: "Collapsible",
    dependencies: ["@radix-ui/react-collapsible"],
    files: ["components/ui/collapsible.tsx"],
  },
  {
    component: "command",
    name: "Command",
    dependencies: ["cmdk"],
    files: ["components/ui/command.tsx"],
  },
  {
    component: "context-menu",
    name: "Context Menu",
    dependencies: ["@radix-ui/react-context-menu"],
    files: ["components/ui/context-menu.tsx"],
  },
  {
    component: "dialog",
    name: "Dialog",
    dependencies: ["@radix-ui/react-dialog"],
    files: ["components/ui/dialog.tsx"],
  },
  {
    component: "dropdown-menu",
    name: "Dropdown Menu",
    dependencies: ["@radix-ui/react-dropdown-menu"],
    files: ["components/ui/dropdown-menu.tsx"],
  },
  {
    component: "hover-card",
    name: "Hover Card",
    dependencies: ["@radix-ui/react-hover-card"],
    files: ["components/ui/hover-card.tsx"],
  },
  {
    component: "input",
    name: "Input",
    files: ["components/ui/input.tsx"],
  },
  {
    component: "label",
    name: "Label",
    dependencies: ["@radix-ui/react-label"],
    files: ["components/ui/label.tsx"],
  },
  {
    component: "menubar",
    name: "Menubar",
    dependencies: ["@radix-ui/react-menubar"],
    files: ["components/ui/menubar.tsx"],
  },
  {
    component: "navigation-menu",
    name: "Navigation Menu",
    dependencies: ["@radix-ui/react-navigation-menu"],
    files: ["components/ui/navigation-menu.tsx"],
  },
  {
    component: "popover",
    name: "Popover",
    dependencies: ["@radix-ui/react-popover"],
    files: ["components/ui/popover.tsx"],
  },
  {
    component: "progress",
    name: "Progress",
    dependencies: ["@radix-ui/react-progress"],
    files: ["components/ui/progress.tsx"],
  },
  {
    component: "radio-group",
    name: "Radio Group",
    dependencies: ["@radix-ui/react-radio-group"],
    files: ["components/ui/radio-group.tsx"],
  },
  {
    component: "scroll-area",
    name: "Scroll-area",
    dependencies: ["@radix-ui/react-scroll-area"],
    files: ["components/ui/scroll-area.tsx"],
  },
  {
    component: "select",
    name: "Select",
    dependencies: ["@radix-ui/react-select"],
    files: ["components/ui/select.tsx"],
  },
  {
    component: "separator",
    name: "Separator",
    dependencies: ["@radix-ui/react-separator"],
    files: ["components/ui/separator.tsx"],
  },
  {
    component: "sheet",
    name: "Sheet",
    dependencies: ["@radix-ui/react-dialog"],
    files: ["components/ui/sheet.tsx"],
  },
  {
    component: "skeleton",
    name: "Skeleton",
    files: ["components/ui/skeleton.tsx"],
  },
  {
    component: "slider",
    name: "Slider",
    dependencies: ["@radix-ui/react-slider"],
    files: ["components/ui/slider.tsx"],
  },
  {
    component: "switch",
    name: "Switch",
    dependencies: ["@radix-ui/react-switch"],
    files: ["components/ui/switch.tsx"],
  },
  {
    component: "table",
    name: "Table",
    files: ["components/ui/table.tsx"],
  },
  {
    component: "tabs",
    name: "Tabs",
    dependencies: ["@radix-ui/react-tabs"],
    files: ["components/ui/tabs.tsx"],
  },
  {
    component: "textarea",
    name: "Textarea",
    files: ["components/ui/textarea.tsx"],
  },
  {
    component: "toast",
    name: "Toast",
    dependencies: ["@radix-ui/react-toast"],
    files: ["components/ui/toast.tsx", "components/ui/use-toast.ts"],
  },
  {
    component: "toggle",
    name: "Toggle",
    dependencies: ["@radix-ui/react-toggle"],
    files: ["components/ui/toggle.tsx"],
  },
  {
    component: "tooltip",
    name: "Tooltip",
    dependencies: ["@radix-ui/react-tooltip"],
    files: ["components/ui/tooltip.tsx"],
  },
]
