name: Validate Registries

on:
  pull_request:
    paths:
      - "apps/v4/public/registries.json"
  push:
    branches:
      - main
    paths:
      - "apps/v4/public/registries.json"

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate registries
        id: validate
        run: |
          set +e
          pnpm --filter=v4 validate:registries
          echo "status=$?" >> $GITHUB_OUTPUT
          exit $?

      - name: Add label to PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const success = '${{ steps.validate.outputs.status }}' === '0';
            const label = success ? 'registries: valid' : 'registries: invalid';

            // Remove opposite label if it exists
            const oppositeLabel = success ? 'registries: invalid' : 'registries: valid';
            try {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                name: oppositeLabel
              });
            } catch (e) {
              // Label might not exist, that's ok
            }

            // Add the appropriate label
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: [label]
            });
